### ISSUE TITLE
Some attributes can't be used as arguments for filter()

### ISSUE THREAD

**Issue by oysteingy** [digitalocean/pynetbox#13]
Hi, 

Thanks (again) for the nice API.

Not a bug per se, more of an feature request. Using pynetbox (2.1.0 / netbox 2.1.4 ), some attributes can't be used as query arguments for model.filter() - despite that Django "permits" it:

This works via nbshell/Django
>>> Interface.objects.filter(device=1, name='gi0')[0].id
1499
lookup ip to interface
>>> IPAddress.objects.filter(interface=1499)[0]
<IPAddress: 10.205.101.43/25>

pynetbox will return the entire dataset for the same query

>>> nb.dcim.interfaces.filter(id=1,name='gi0')[0].id
1499
>>> nb.ipam.ip_addresses.filter(interface=1499)

Returns all IPaddresses 

nb.ipam.ip_addresses.filter(description='FOO')

Returns all IPaddresses

This works as expected however:

nb.ipam.ip_addresses.filter(family=6)
nb.ipam.ip_addresses.filter(status=3) 
nb.ipam.ip_addresses.filter('10.0.0.0/32')

**Comment by zachmoody** [comment]
Hey @oysteingy 

I didn't have time to reproduce, so if let me know if I'm off with my explanation. The django shell can filter on any field in the database, but there's a more limited set of fields available to filter on in the API. E.g. if you're looking for what filters you can pass to the interfaces endpoint, they're defined [here](https://github.com/digitalocean/netbox/blob/develop/netbox/dcim/filters.py#L523-L550). Unfortunately, it doesn't look as though `name` is available right now.

Those variables that are `django_filter` objects are basically the named args you can pass to `.filter()` in pynetbox (`device`, `device_id `, `mac_address`, etc.). The reason you're getting the whole dataset is that's default NetBox behavior when you pass a filter that isn't defined.

**Comment by oysteingy** [comment]
Hi, 

Sorry, this is just me being silly. After looking at the available query arguments for IPAM [https://github.com/digitalocean/netbox/blob/develop/netbox/ipam/filters.py](here)  the stars aligned for me .

'interface' is a valid query arguments in Django/nbshell, but not in the API.
'interface_id', however is available in the API for queries. 


Sorry for the mess, and thank you very much for your help.
