### ISSUE TITLE
Use Requests Param to build URL instead of Request.url

### ISSUE THREAD

**Issue by zachmoody** [digitalocean/pynetbox#133]

**Comment by tyler-8** [comment]
pynetbox currently does [URL query building](https://github.com/digitalocean/pynetbox/blob/master/pynetbox/core/query.py#L146) on its own.

However, requests [already does this](http://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls) by passing `params` in the `get` request. Probably better to leave as much to requests as possible.
