### ISSUE TITLE
Virtualization support

### ISSUE THREAD

**Issue by maximebrun** [digitalocean/pynetbox#14]
Hi,

Thanks for the lib.

Do you plan to add virtualization support in pynetbox in the near futur ?

**Comment by zachmoody** [comment]
Yes, soon ™  :)

I don't think it would be much more involved than adding the attribute when `Api()` inits to get it to work, but we'd also probably want to add tests and fixtures.

**Comment by iDemonix** [comment]
Trying to sync an enormous VMWare environment up to NetBox, would love to see it implemented to save me having to hack Python scripts together!

**Comment by iDemonix** [comment]
I've added the attribute to the `Api` initialisation, and it seems to work for me. I'd create a PR but I'm more of a hack-coder and don't know enough about unit tests.
