### ISSUE TITLE
connected_device.get is broken

### ISSUE THREAD

**Issue by tkupari** [digitalocean/pynetbox#142]
There is a problem when calling /dcim/connected-device/ endpoint with required filters 

```
nb.dcim.connected_device.get(peer_device=device_name, peer_interface=interface_name)

...

AttributeError: 'str' object has no attribute 'items'
```

Reason for this seems to be that connected_device returns only one result, but it is being handled like other filter results.

**Comment by zachmoody** [comment]
That endpoint's something of an outlier. It's been around quite a while and is unlike any of the other endpoints, but let me try and find out its future before I say if we can support it or not. In the meantime I think you can use something like this to get the same functionality.
```
x = nbapi.dcim.interfaces.get(device="hostname", name="if_name")
print(x.connected_endpoint.device.name)
```

**Comment by tkupari** [comment]
Ok, thanks for the reply. I will use that one.
