### ISSUE TITLE
python3: pynetbox cannot be loaded?

### ISSUE THREAD

**Issue by misch42** [digitalocean/pynetbox#143]
Hi,

I installed netbox, salt and pynetbox on a new ubuntu 18.04 (bionic). I configured an external pillar according to the docs (/etc/salt/master)

ext_pillar:
  - netbox:
    api_url: http://127.0.0.1/api/
    api_token: XXXXX 
    proxy_return: True
    proxy_username: admin

But salt isn't able to use the pillar:

# salt myswitch netbox.get dcim devices 
myswitch:
    'netbox' __virtual__ returned False: The netbox execution module cannot be loaded: pynetbox library is not installed.
ERROR: Minions returned with non-zero exit code

# salt -V
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.2
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Ubuntu 18.04 bionic

# pip3 list  | grep netbox
pynetbox (4.0.6)

Any ideas?

**Comment by zachmoody** [comment]
pynetbox would need to be installed on the minion, or whatever hosts the proxy-minion, but this isn't the right repo to open this issue under. I'd reopen under the salt repo if you're still having problems.

**Comment by misch42** [comment]
#51140 in salt.
