### ISSUE TITLE
Creating region with parent region does not establish relationship

### ISSUE THREAD

**Issue by tyler-8** [digitalocean/pynetbox#145]
```
pynetbox==4.0.6
netbox==2.5.3
```

The new region is created, but the parent_id field doesn't appear to get passed properly. The same request works using the `requests` module. The GUI also shows the new region but no relationship to the specific parent.

```
>>> parent = nb.dcim.regions.get(84)
>>> parent
Northern

>>> parent.id
84

>>> reg = nb.dcim.regions.create({'name': 'test region', 'slug': 'test-region', 'parent_id': 84})
>>> reg
test region

>>> reg.parent
```

**Comment by zachmoody** [comment]
Thanks for the report, will have a look.

**Comment by tyler-8** [comment]
I think I'm seeing the same behavior with adding sites with a tenant_id. Passing a valid tenant_id when creating a site doesn't build the relationship. 2.5.3 and 2.5.4 seem to have the issue.

**Comment by tyler-8** [comment]
The ID is passed to `parent`, not `parent_id` - that was the issue. Closing!

**Comment by zachmoody** [comment]
Oh, that's right. You see the `whatever_id` convention a lot in URL params. Didn't look off to me at first either. Thanks for reporting back!
