### ISSUE TITLE
How to create interface connections?

### ISSUE THREAD

**Issue by jkrauska** [digitalocean/pynetbox#15]
Was really hoping this would work.

```
int_a = nb.dcim.interfaces.get(name='xe-4/0/16', device='BLAHSWITCH')
int_b = nb.dcim.interfaces.get(name='eth3', device='BLAHHOST')
nb.dcim.interface_connections.create(
    interface_a=int_a,
    interface_b=int_b)
```

It gives:
TypeError: eth3 is not JSON serializable

Any advice on how to create new interface_connections?

The interfaces are loaded just fine, it's the connections I'm stuck on.

v2.2.1

**Comment by zachmoody** [comment]
It’s looking for the id there, iirc. Try ‘int_a.id’.

**Comment by soer7022** [comment]
This doesn't seem to work anymore... I get the following error upon trying to create the interface connection:
`pynetbox.core.query.RequestError: The request failed with code 405 Method Not Allowed: {u'detail': u'Method "POST" not allowed.'}`

**Comment by zachmoody** [comment]
If you're using 2.6 `interface_connections` has been supplanted by the `cables` work and won't take POSTs anymore.

**Comment by soer7022** [comment]
Thanks that solved the problem
