### ISSUE TITLE
PUT method to overwrite any old data of devices like a fresh device for same device_id in netbox

### ISSUE THREAD

**Issue by shivam2612** [digitalocean/pynetbox#151]
Hi,
I'm beginner. Please guide me if I'm wrong.

My query:
Is there any PUT method in _pynetbox_ which does exactly as PUT in /api/dcim/devices/{id}/ ? As far as I know save() or update() will only overwrite fields which I specify explicitly. 

For example, I want to erase all the old data of a devices and want to update new data for same device_id. The save() will work fine if new data has all the fields which are in old data. And if there are some non-compulsory extra fields in old data which are not in new data, these extra fields will not get NULL (or default) value like a fresh devices and old value of those fields will remain in case of save() or update(). But in case of PUT in /api/dcim/devices/{id}/ , these absent fields in new data (present in old data) will automatically get erased or get default value.

I know I can use loop on each fields of object and assign NULL (or default) for absent fields in new data (present in old data) and then save object with new values of only required fields. 

If there is such PUT method for devices (or dcim), please tell me how to use it as I'm not able to find it.
If there is no such method, can it be implemented?

**Comment by zachmoody** [comment]
Unfortunately that's a pretty niche use-case we probably won't plan on supporting unless there's tons of requests for it.
