### ISSUE TITLE
JSONDecodeError when trying to allocate larger prefix than fits

### ISSUE THREAD

**Issue by markkuleinio** [digitalocean/pynetbox#156]
Python: 3.5.3
NetBox: 2.5.8
pynetbox: 4.0.6

When trying to create a prefix within a prefix with `available_prefixes.create()`, a `JSONDecodeError` exception is raised when the request cannot be fulfilled. I would expect RequestError or something like that. Am I doing something incorrectly?

Example:

```
>>> prefix = netbox.ipam.prefixes.get(prefix="10.1.0.0/16")
>>> prefix
10.1.0.0/16
>>> netbox.ipam.prefixes.filter(within="10.1.0.0/16")
[10.1.10.0/24]
>>>
>>> newlongprefix = prefix.available_prefixes.create( {'prefix_length':17} )
>>> netbox.ipam.prefixes.filter(within="10.1.0.0/16")
[10.1.10.0/24, 10.1.128.0/17]
>>>
>>> newlongprefix = prefix.available_prefixes.create( {'prefix_length':17} )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pynetbox/core/endpoint.py", line 352, in create
    return Request(**self.request_kwargs).post(data)
  File "/usr/local/lib/python3.5/dist-packages/pynetbox/core/query.py", line 293, in post
    return req.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>>
>>> netbox.ipam.prefixes.filter(within="10.1.0.0/16")
[10.1.10.0/24, 10.1.128.0/17]
>>>
```

**Comment by zachmoody** [comment]
:thinking: wonder what NetBox is sending back. Can you try with curl and paste the response?

**Comment by markkuleinio** [comment]
Starting set:
```
>>> netbox.ipam.prefixes.filter(within="10.1.0.0/16")
[10.1.10.0/24]
```

First /17 allocation with curl:
```
$ curl -X POST "http://netbox.server/api/ipam/prefixes/10/available-prefixes/" -H "accept: application/json; indent=4" -H "Content-Type: application/json" -H "Authorization: Token xxx" -d "{ \"prefix_length\": 17}"
{
    "id": 18,
    "family": {
        "value": 4,
        "label": "IPv4"
    },
    "prefix": "10.1.128.0/17",
    "site": null,
    "vrf": null,
    "tenant": null,
    "vlan": null,
    "status": {
        "value": 1,
        "label": "Active"
    },
    "role": null,
    "is_pool": false,
    "description": "",
    "tags": [],
    "created": "2019-04-14",
    "last_updated": "2019-04-14T12:02:47.243174Z"
}
$
```

= success (as it should be). Current situation:
```
>>> netbox.ipam.prefixes.filter(within="10.1.0.0/16")
[10.1.10.0/24, 10.1.128.0/17]
```
Second allocation attempt with curl (should fail as there is no room for another /17 anymore):
```
$ curl -X POST "http://netbox.server/api/ipam/prefixes/10/available-prefixes/" -H "accept: application/json; indent=4" -H "Content-Type: application/json" -H "Authorization: Token xxx" -d "{ \"prefix_length\": 17}"
$
```

= nothing is returned, instead of any error message. Is this a NetBox issue, or is it intentional that some requests just return nothing, and pynetbox should cope with that?

(This run was tested now with NetBox 2.5.10)

**Comment by zachmoody** [comment]
Yeah, I'd take a guess that a 2XX response here is not ideal. Maybe open an issue over on NetBox's repo and see if that's desired behavior. If it is, we can probably do something in pynetbox to account for it.

**Comment by markkuleinio** [comment]
I see now that you already discussed it last year in [https://github.com/digitalocean/netbox/issues/2602#issuecomment-440406030](https://github.com/digitalocean/netbox/issues/2602#issuecomment-440406030).

**Comment by zachmoody** [comment]
:man_facepalming: thanks for finding that! I'd completely forgotten about that conversation. So sounds like we'll need to sort this out in pynetbox. I'm not entirely sure when I'm going to get some time to address it, but I'll mark this as a bug then.

**Comment by markkuleinio** [comment]
I submitted a PR to add AllocationError for more convenient detection of unsuccessful allocation.
