### ISSUE TITLE
constant ids are not transparent on the API neither on the documentation

### ISSUE THREAD

**Issue by trunet** [digitalocean/pynetbox#157]
Hello all...

Thanks for this excellent CMDB, I really appreciate it.

I'm on a project to phase out racktables in favor of netbox. I'm writing an agent that will run on all the servers, vms, cloud instances to collect hardware, network, ..., information and push to netbox.

Per example, I have some servers with SFP+, some with 1000baseT. To push the correct data to netbox, I need to go to the constants files present on netbox server and get IFACE_FF_1GE_FIXED or IFACE_FF_10GE_SFP_PLUS ID from there. My workaround for now is to get all the constants.py files and include on my agent package so I can just "import" and use.

I don't know exactly how would you like to improve this. I can suggest 3 approaches:
1) include all constants.py on this wrapper
Downside is to sync the files every time there's a constants change on the main netbox package.
2) pynetbox can use constant name and list these constants on the documentation (depends on point 1. in a way)
3) main netbox server api should have a way to API query this constants

List of constants.py
```
./netbox/utilities/constants.py
./netbox/circuits/constants.py
./netbox/ipam/constants.py
./netbox/extras/constants.py
./netbox/virtualization/constants.py
./netbox/dcim/constants.py
```

Thank you!

**Comment by tyler-8** [comment]
You'll find the constants under the various `/choices/` endpoints in the Netbox REST API documentation at `http://<netbox-url>/api/docs/`

**Comment by trunet** [comment]
found it. thanks :D
