### ISSUE TITLE
Filter empty custom fields

### ISSUE THREAD

**Issue by diegoroccia** [digitalocean/pynetbox#160]
I created a warranty custom field (type date) and I want to filter all the servers with NO warranty set. I tried with the following:

```
nb.dcim.devices.filter(tenant="myteam",cf_warranty=None)
nb.dcim.devices.filter(tenant="myteam",cf_warranty="")
```

but I didn't get it to work. I ended up using a python filter but I wanted to know if I can get the exact result directly from the API

**Comment by zachmoody** [comment]
Afaik, this isn't something that's supported in the NetBox API. Afraid the only way to do it is filtering the results like you've done.

**Comment by kimdoy17** [comment]
Has there been an update on this?
