### ISSUE TITLE
Allow passing a timeout parameter at API at creation time

### ISSUE THREAD

**Issue by chaomodus** [digitalocean/pynetbox#166]
It would be very useful if we could specify a timeout value that would be passed to `requests` operations as its timeout parameter, perhaps as an extra parameter to pynetbox.API().

**Comment by zachmoody** [comment]
:wave:  you should be able to do this, though not as an init kwarg. Have some [examples in the docs](https://pynetbox.readthedocs.io/en/latest/advanced.html#timeouts).
