### ISSUE TITLE
Proxy Error when callig netbox_auth.dcim.interfaces.all()

### ISSUE THREAD

**Issue by firefly-serenity** [digitalocean/pynetbox#169]
CentOS Linux release 7.6.1810 (Core)
python 3.6 via software collections
netbox 2.5.12
pynetbox in /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages (4.0.6)

While other requests work perfectly fine, this one fails and I do not know why:

`>>> netbox_auth.dcim.interfaces.all()`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pynetbox/core/endpoint.py", line 98, in all`
`    return [self._response_loader(i) for i in req.get()]`
`  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pynetbox/core/query.py", line 239, in get`
`    return req_all(self.url)`
`  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pynetbox/core/query.py", line 232, in req_all`
`    req = make_request(next_url)`
`  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pynetbox/core/query.py", line 214, in make_request`
`    raise RequestError(req)`
`pynetbox.core.query.RequestError: The request failed with code 502 Proxy Error but more specific details were not returned in json. Check the NetBox Logs or investigate this exception's error attribute.`

**Comment by firefly-serenity** [comment]
Problem solved: gunicorn timeout to short

**Comment by mrfroggg** [comment]
got the same issue with a few tens of thousands of devices in Netbox, req_all() takes too long and the http connection times out. I'll look into my http server, but from the look of the code, a refractor from this function could help to speed this up.
