### ISSUE TITLE
interface type id

### ISSUE THREAD

**Issue by tommydpl** [digitalocean/pynetbox#171]
I'm trying to automate switch cration using netbox api and python and cannot figure out how to find needed interface `form_factor` id. Is there an equivalent of `nb.dcim.device_roles.get(slug='access-switch') ` for interfaces? 
I only see examples using an arbitrary ID like: 

```
intf = dict(
    name="Vl841",
    form_factor=0,
    description="Management SVI",
    device=new_dev["id"]
)
```

**Comment by soer7022** [comment]
Create a device in netbox with the form factor you want and make a get request on that device to find the form factor

**Comment by zachmoody** [comment]
^ that would work. It's also exposed in NetBox via the `api/dcim/_choices` endpoint, which is available in pynetbox as the `.choices()` [method](https://pynetbox.readthedocs.io/en/latest/#pynetbox.api.App.choices) off the App object. Which you could use with something like:
```
nb.dcim.choices()['interface:type']
```
