### ISSUE TITLE
how to get ID of tenant

### ISSUE THREAD

**Issue by ognjen011** [digitalocean/pynetbox#173]
I am creating tenants sites and devices. So far everything works except trying ti get an ID of a tenant. How do i accomplish that?

ndev_tenant = nb.tenancy.tenants.get(slug=tenant)
    req_fields = (
    "Tenant: {tenant}, ID: {tenant_id}\n".format(
        tenants=ndev_tenant,
        tenant_id=ndev_tenant.id,
    )
)

File "create_tenant.py", line 38, in <module>
    tenant_id=ndev_tenant.id,
KeyError: 'tenant'

**Comment by zachmoody** [comment]
Not sure, seems to work for me:

```
>>> import pynetbox
>>> nb = pynetbox.api('https://test')
>>> nb.tenancy.tenants.get(slug='lab')
Lab
>>> x = nb.tenancy.tenants.get(slug='lab')
>>> x.id
4
>>> 
```
