### ISSUE TITLE
why does query.Requests.req_all paginate and not just set limit to 0?

### ISSUE THREAD

**Issue by danaronson** [digitalocean/pynetbox#174]
Since netbox 2.0.5 pagination can be disabled (https://github.com/netbox-community/netbox/issues/1237).  Why doesn't req_all use this?

**Comment by berahtlv** [comment]
If I understood correctly, it always requests all results `req = make_request(url)` and depending on server config `MAX_PAGE_SIZE` response will have `"next"` attribute and in the case of pagination additional request will be done `while req["next"]: ... ret.extend(req["results"])`

**Comment by berahtlv** [comment]
I'm getting `502 Bad Gateway` for requests that takes more than 30 seconds. In case of our installation that error occur with `pynetbox` and `curl` for responses longer than 5500 values (dcim.devices).

**Comment by danaronson** [comment]
req_all does not actually use the url for req['next'] the first time, but tries to be greedy and get all of the results.  As @berahtlv points out, that can sometimes cause timeouts.

**Comment by zachmoody** [comment]
It's only as greedy as you allow it to be with `MAX_PAGE_SIZE`.
