### ISSUE TITLE
Bulk Delete?

### ISSUE THREAD

**Issue by lamoni** [digitalocean/pynetbox#175]
Is it possible to batch delete devices, sites, etc...?

Currently, I'm looping through .dcim.devices.all() and calling delete() per object in that list, but it can take quite awhile as that's an HTTP request per device/site/whatever

Thanks!

**Comment by zachmoody** [comment]
I'm afraid not, the NetBox API only accepts DELETE on detail endpoints currently so you'd need the object's id to delete anyways.

**Comment by lamoni** [comment]
For future reference, issue on netbox github is discussed here. Seems there is support for the idea, so hopefully this will be a possibility in the future: https://github.com/netbox-community/netbox/issues/3436
