### ISSUE TITLE
unable to update tagged_vlans set

### ISSUE THREAD

**Issue by bytereisender** [digitalocean/pynetbox#176]
hi folks,

is there a way to update a specific existing tagged vlan entry inside "tagged_vlans", with multiple existing entries inside? every time i tried to save or update i got nothing back: no error message - nothing ... like when it runs successfully. but when i refresh the corresponding page inside netbox there is nothing updated. 

for "untagged_vlan" everything works fine, but the construct there is a little bit different (there is no set inside).

the documentation for this particular situation (updating a "tag" or "tagged_vlans" entry (set)) is poor and you will find no useful examples or explanations in the web. so please explain me how to realize it - straight forward, like a documentation entry for updating tagged vlans :)

**Comment by zachmoody** [comment]
Hrm, it should work, but can't say I do that anywhere with pynetbox. Can you send a code example?

**Comment by bytereisender** [comment]
I think I found a solution for me, but its not with update() like it working with untagged_vlan:


```
vlanOldVid = 111
vlanNewVid = 222

### Load interface data
interfaceList = nb.dcim.interfaces.filter(device = "Server-01")
for interfaceItem in range(len(interfaceList)) :
    interface = interfaceList[int(interfaceItem)]

### Untagged VLAN update
untaggedVlan = interface.untagged_vlan

if (untaggedVlan.vid == int(vlanOldVid)):
    interface.update({ "untagged_vlan" : { "vid" : int(vlanNewVid) } })
```

Thats really simple so far...

But for tagged vlans I've to manipulate the list of vlans inside of "tagged_vlans".  In this case the update() function is accepting my input - at least it seems like it does - but in netbox itself nothing was changed/updated. You you won't get any error message - the terminal looks like as if it was working properly.

Thats the reason why I played around a bit and found the following working solution for my individual intentions :

```
vlanOldVid = 111
vlanNewVid = 222

### Load original VID data
vlanOldVidFull = nb.ipam.vlans.filter(vid = vlanOldVid)

for vlanOldVidItem in range(len(vlanOldVidFull)):
    vlanOldVidEntry = vlanOldVidFull[int(vlanOldVidItem)]

### Load target VID data
vlanNewVidFull = nb.ipam.vlans.filter(vid = vlanNewVid)

for vlanNewVidItem in range(len(vlanNewVidFull)):
    vlanNewVidEntry = vlanNewVidFull[int(vlanNewVidItem)]

### Load interface data
interfaceList = nb.dcim.interfaces.filter(device = "Server-01")
for interfaceItem in range(len(interfaceList)) :
    interface = interfaceList[int(interfaceItem)]

### Tagged VLAN update
for taggedItem in range(len(interface.tagged_vlans)):
    loopCounter = 0
    while (loopCounter <= len(interface.tagged_vlans)):
        taggedVlan = interface.tagged_vlans[loopCounter]

        if (int(interface.tagged_vlans[loopCounter].vid) == int(vlanOldVid)):
            interface.tagged_vlans.remove(interface.tagged_vlans[loopCounter])
            interface.tagged_vlans.append(vlanNewVidEntry)
            interface.save()
```

Nevertheless I'm really interested if there exist a solution in update() syntax, so if thou hast any idea... :)

**Comment by markkuleinio** [comment]
update() works here with Python 3.7.3, pynetbox 4.0.8 and NetBox 2.6.1:

```
>>> v100 = netbox.ipam.vlans.get(2)
>>> v100
Vlan100
>>> v100.id
2
>>> v101 = netbox.ipam.vlans.get(3)
>>> v101
Vlan101
>>> v101.id
3
>>> i = netbox.dcim.interfaces.get(9)
>>> i.serialize()
{'id': 9, 'device': 1, 'name': 'eth0', 'type': 1000, 'form_factor': 1000, 'enabled': True, 'lag': None, 'mtu': None, 'mac_address': None, 'mgmt_only': False, 'description': '', 'connected_endpoint_type': None, 'connected_endpoint': None, 'connection_status': None, 'cable': None, 'mode': 200, 'untagged_vlan': None, 'tagged_vlans': [2], 'tags': [], 'count_ipaddresses': 0}
>>> i.update({"tagged_vlans": [v101]})
True
>>> i.serialize()
{'id': 9, 'device': 1, 'name': 'eth0', 'type': 1000, 'form_factor': 1000, 'enabled': True, 'lag': None, 'mtu': None, 'mac_address': None, 'mgmt_only': False, 'description': '', 'connected_endpoint_type': None, 'connected_endpoint': None, 'connection_status': None, 'cable': None, 'mode': 200, 'untagged_vlan': None, 'tagged_vlans': [3], 'tags': [], 'count_ipaddresses': 0}
>>>
```

`tagged_vlans` is a list, so just take the list in a variable, manipulate it as you wish, and then replace the list in the interface object with update().

**Comment by HarishankarYellapragada** [comment]
Unable to update using update. Manually updated MG interface. So, I can see that

    interface = nb.dcim.interfaces.get(device=device.name, name="TenGigabitEthernet1/50")
    print("Interface name:", interface.name)
    print("Interface tagged vlans:", interface.tagged_vlans)
    vlan_obj = nb.ipam.vlans.get(vid = 9, group_id=3)
    print("VLAN name:",vlan_obj.name, vlan_obj.vid , "| id: ",vlan_obj.id)
    print("vlan id:", vlan_obj.id)
    vlan_obj.update({'tagged_vlans': [27]})   //Used a different Vlan id manually 
    print("tagged_vlans:", interface.tagged_vlans)
---------------
output:
---------------
  Device name: switch-A
  Interface name: TenGigabitEthernet1/50
  Interface tagged vlans: [MG]
  VLAN name: Inside 9 | id:  27
  vlan id: 27
  tagged_vlans: [MG]
