### ISSUE TITLE
Parameter to increase HTTP connection pool size

### ISSUE THREAD

**Issue by tyler-8** [digitalocean/pynetbox#189]
With https://github.com/digitalocean/pynetbox/pull/148 (using `requests` sessions) being merged, `pynetbox` is poised for better use in multithreading code. However, one piece needs to be added in order to prevent errors when running threads sharing the same `pynetbox.Api` object.

`requests` allows [mounting of HTTP Adapters](https://requests.kennethreitz.org/en/master/user/advanced/#transport-adapters) (which are using `urllib3` under the hood. Increasing the pool size allows the connection pool to [cache more connections](https://urllib3.readthedocs.io/en/1.4/pools.html). 

I envision this update going somewhere around https://github.com/digitalocean/pynetbox/blob/master/pynetbox/api.py#L143
```
self.http_session = requests.Session()
adapter = requests.adapters.HTTPAdapter(pool_connections=4, pool_maxsize=4)
self.http_session.mount('http://', adapter)
self.http_session.mount('https://', adapter)
```

And perhaps the poolsize can be customized at object instantiation like

```
nb = pynetbox.Api(url, token=token, ssl_verify=True, poolsize=4)
```

with a default of 1 (the `urllib3` default).

**Comment by zachmoody** [comment]
Yeah, makes sense, but nosing around the requests repo [seems to indicate](https://github.com/psf/requests/blob/d2590ee46c0641958b6d4792a206bd5171cb247d/requests/adapters.py#L84) the default is 10 for both pool kwargs.

**Comment by tyler-8** [comment]
Good find! Here I just assumed `requests` was using the default to begin with. I still think exposing that functionality is a good move. I'll work on a PR for your review.

**Comment by mrfroggg** [comment]
Good idea! I'm using a lot of threads in my script and I'm hitting the limit quite fast.

**Comment by tyler-8** [comment]
A thought occurred to me. Is any of this necessary? You could just do...

```python

nb = pynetbox.Api(url, token=token)
adapter = requests.adapters.HTTPAdapter(pool_connections=10, pool_maxsize=10)
nb.http_session.mount('http://', adapter)
nb.http_session.mount('https://', adapter)
```

And end up with the same result I think. You could craft an entirely custom `Session` object from `requests`.
