### ISSUE TITLE
VERSION File not copied while installing from git clone

### ISSUE THREAD

**Issue by tweippert** [digitalocean/pynetbox#19]
Hi, 

If i use a fresh clone from version 3.0.0 i get an error, that the VERSION File is missing in the installation (with python3). Can this be reproduced by someone? 

```
Traceback (most recent call last):
  File "./create-dhcp-from-netbox.py", line 3, in <module>
    import pynetbox
  File "/usr/lib/python3.6/site-packages/pynetbox-3.0.0-py3.6.egg/pynetbox/__init__.py", line 5, in <module>
    with open(join(dirname(__file__), 'VERSION')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.6/site-packages/pynetbox-3.0.0-py3.6.egg/pynetbox/VERSION'

```
If i copy the VERSION file manually to "/usr/lib/python3.6/site-packages/pynetbox-3.0.0-py3.6.egg/pynetbox/lib/" the packages works (beneath the urlencode change, see my pull-request).

regards, 
tim

**Comment by zachmoody** [comment]
Thanks for the report! Should be fixed now.
