### ISSUE TITLE
Implement threading for .all() and .filter() requests

### ISSUE THREAD

**Issue by tyler-8** [digitalocean/pynetbox#191]
When pulling a large dataset from Netbox, it can take quite a long time for `pynetbox` to retrieve all the paginated results as it pulls them serially. Implementing multi-threading will have drastic performance improvements.

```
querying 45K VLANs through the API with page limit of 1000:

type                               seconds
pynetbox                           108.5
requests w/ session                92.0
requests session multithreaded     22.9
```

The way I've done it locally is using a `ThreadPoolExecutor` from `concurrent.futures` and doing an initial request to get the total (`count`), and calculating the total number of pages and correct offsets. As you can see in the numbers above, the speed improvements are significant.

The only thing I haven't yet looked in to is how to determine the `MAX_PAGE_SIZE` dynamically. My first thought is to make the initial request with `limit=0` and then count the length of the `results` array - but happy to hear an alternative way.

Would it make more sense to make these separate methods altogether? Something like `.all_fast()` and `.filter_fast()` or something to that effect? Or possibly `.all(fast=True)` and `.filter(fast=True)` - but that would introduce some additional parsing of the args that the user passes in.

**Comment by zachmoody** [comment]
Just tossing out an idea, it could be a kwarg we pass on init, e.g. `.api(threading=True)`, that let the user just generally signal they wanted to thread when available. There's been a few issues to optimize `.all()`, but I'm usually a little hesitant to add complexity there because I genuinely have a hard time understanding use-cases that can't filter to _some_ extent (a bit naive, I know). :smile:

**Comment by tyler-8** [comment]
> let the user just generally signal they wanted to thread when available

I like that idea too - makes things even simpler. 

>  I genuinely have a hard time understanding use-cases that can't filter to some extent

Everyone's environment is going to be different of course, but generally, even with filtering, I'm going to be in the several thousand items ballpark for each endpoint - of which I have to hit several. That request time stacks up quickly.
