### ISSUE TITLE
cannot access /api/extras/_custom_field_choices endpoint

### ISSUE THREAD

**Issue by brokenjacobs** [digitalocean/pynetbox#200]
Callling:
```python
nb.extras._custom_field_choices.all()
```

Results in pynetbox sanitizing the _ to a - for some reason?
```
pynetbox.core.query.RequestError: The requested url: https://MYNETBOXHOST/api/extras/-custom-field-choices/ could not be found.
```

**Comment by markkuleinio** [comment]
Looking at `api.py` I see there is no `App` method for `_custom_field_choices` so that needs to be written. I've never used custom field choices so maybe I'll have a look at that at some point and implement the method, unless @zachmoody has other views on this.

**Comment by zachmoody** [comment]
Sounds like a good plan, unfortunate we have to add another special method just as we're talking about being able to get rid of `.choices()` :cry:. Thinking maybe a `.custom_choices()` method that's similar to `.choices()` but we raise `NotImplemented` if `self.name` is anything other than extras, what do you think?

**Comment by markkuleinio** [comment]
Sounds good. I only now realized that `/_choices` also accept an `id`, like `prefix:status`... 😄 The `/_custom_field_choices` also does that, I will have to test the custom values first.

**Comment by markkuleinio** [comment]
For the record, that's how the API output looks like for two custom fields, both having two different selectable options:

```
$ curl -H "Authorization: Token xxx" -H "Accept: application/json; indent=4" \
http://netbox.example.local/api/extras/_custom_field_choices/
{
    "Testfield": {
        "Test2": 2,
        "Test1": 1
    },
    "Testfield2": {
        "TF2": 4,
        "TF1": 3
    }
}

$ curl -H "Authorization: Token xxx" -H "Accept: application/json; indent=4" \
http://netbox.example.local/api/extras/_custom_field_choices/Testfield2/
{
    "TF2": 4,
    "TF1": 3
}
```

Looks like it could be possible to write a method like `custom_choices(self, field_name=None, value=None)` where the caller can optionally specify the `field_name` or `field_name` + `value` to get just the value that's needed.
