### ISSUE TITLE
Pagination infinite loop

### ISSUE THREAD

**Issue by volans-** [digitalocean/pynetbox#206]
I'm getting what seems to be an infinite loop of calls where the GET parameters are always appended.
For example calling `netbox.dcim.interfaces.filter(mgmt_only=True)` where `netbox` is an instance of `pynetbox.api`, those are the calls as logged with debug level:
```
GET /api/dcim/interfaces/?mgmt_only=True
GET /api/dcim/interfaces/?mgmt_only=True&limit=1345&offset=50
GET /api/dcim/interfaces/?limit=1000&mgmt_only=True&offset=1050&mgmt_only=True&limit=1345&offset=50
GET /api/dcim/interfaces/?limit=1000&mgmt_only=True&mgmt_only=True&offset=1050&mgmt_only=True&limit=1345&offset=50
GET /api/dcim/interfaces/?limit=1000&mgmt_only=True&mgmt_only=True&mgmt_only=True&offset=1050&mgmt_only=True&limit=1345&offset=50
GET /api/dcim/interfaces/?limit=1000&mgmt_only=True&mgmt_only=True&mgmt_only=True&mgmt_only=True&offset=1050&mgmt_only=True&limit=1345&offset=50
[...SNIP...]
```

For reference the current setting for `MAX_PAGE_SIZE` in the Netbox server is the default `1000`.

Calling instead the API directly for `GET /api/dcim/interfaces/?mgmt_only=True` I get as next page:
```
"next": "https://$HOSTNAME/api/dcim/interfaces/?limit=50&mgmt_only=True&offset=50",
```
And calling `GET /api/dcim/interfaces/?mgmt_only=True&limit=1345&offset=50` (pynetbox's second call) I get as next page:
```
"next": "https://$HOSTNAME/api/dcim/interfaces/?limit=1000&mgmt_only=True&offset=1050",
```
That would actually allow to correctly loop over the results, but pynetbox seems to be appending the previous parameters too.

Pynetbox version used: `4.2.0`

**Comment by volans-** [comment]
As a workaround you can increase/disable the `MAX_PAGE_SIZE` so that the second call will be able to gather them all.

**Comment by markkuleinio** [comment]
Which version of pynetbox are you using? There were some URL parameter changes in 4.1.0.

**Comment by volans-** [comment]
@markkuleinio sorry I missed to mention that in the description: `pynetbox==4.2.0`

**Comment by markkuleinio** [comment]
I can confirm this. `ii = netbox.dcim.interfaces.filter(name="Loopback")`, from Apache logs, with pynetbox 4.0.8:

```
GET /api/dcim/interfaces/?name=Loopback
GET /api/dcim/interfaces/?name=Loopback&limit=2019&offset=200
GET /api/dcim/interfaces/?limit=1000&name=Loopback&offset=1200
```
With pynetbox 4.2.0:
```
GET /api/dcim/interfaces/?name=Loopback
GET /api/dcim/interfaces/?offset=200&name=Loopback&limit=2019
GET /api/dcim/interfaces/?limit=1000&name=Loopback&offset=1200&offset=200&name=Loopback&limit=2019
GET /api/dcim/interfaces/?limit=1000&name=Loopback&name=Loopback&offset=1200&offset=200&name=Loopback&limit=2019
...
```
(the output "never" completes)

**Comment by markkuleinio** [comment]
Apache log after #207 was implemented, with the same example `ii = netbox.dcim.interfaces.filter(name="Loopback")`:

```
GET /api/dcim/interfaces/?name=Loopback
GET /api/dcim/interfaces/?limit=2019&name=Loopback&offset=200
GET /api/dcim/interfaces/?limit=1000&name=Loopback&offset=1200
```
(`len(ii)` = 2019)

**Comment by mrfroggg** [comment]
Also facing this issue on interfaces, I'm getting some random 414 URI too long errors with loops of the parameter I sent to find a device's interfaces
