### ISSUE TITLE
Fail to hash response records as 'Endpoint' object has no attribute 'name'

### ISSUE THREAD

**Issue by volans-** [digitalocean/pynetbox#208]
I'm getting errors if trying to hash some records returned by the api. In my case I was adding them to a `set()`.
The error that I'm getting is:
```
    File pynetbox/core/response.py", line 218, in __hash__
        return hash((self.endpoint.name, self.id))
AttributeError: 'Endpoint' object has no attribute 'name'
```
And indeed if I manually get a record, let's say with:
```
api.dcim.devices.get(1)
```
Its `.endpoint` doesn't have a `name` property.
From a quick look at the `Endpoint` class implementation, it seems that the `name` passed to it doesn't get stored in the instance.
It seems to me that the issue was introduce in the recent #196 and that a quick way to fix it is to change it to: `self.endpoint.return_obj.__name__` if I understand the intention there.
The tests are passing because the whole `Endpoint` object is mocked and the `name` property manually set.

Tested with `pynetbox 4.2.1`.

**Comment by fach** [comment]
A fix for this is in 4.2.2 which was released yesterday so you should be good to close this issue.
