### ISSUE TITLE
Basic auth in front of netbox

### ISSUE THREAD

**Issue by xsgb** [digitalocean/pynetbox#209]
Hello, would it be possible to pass basic HTTP authentication parameters to requests without modifying pynetbox internally ? Doing something like this for the requests:

```python
requests.get('https://frontal/netbox/', auth=('user', 'pass'))
```
I've actually tried passing my test credentials in the url using the `user:pass@host` format but request seems to ignore it.
```
>>> nb.dcim.devices.all()
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1006: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/endpoint.py", line 98, in all
    return [self._response_loader(i) for i in req.get()]
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/query.py", line 239, in get
    return req_all(self.url)
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/query.py", line 217, in req_all
    req = make_request(url)
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/query.py", line 214, in make_request
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 403 Forbidden: {'detail': 'Authentication credentials were not provided.'}
>>>
```

**Comment by hSaria** [comment]
I don't think basic authentication is [supported by NetBox](https://netbox.readthedocs.io/en/stable/api/authentication/), but I think you're referring to authentication to the frontend web server (e.g. `Basic` auth type for httpd) followed by authentication to the backend one (e.g. `Token` auth type to gunicorn), right? If so, I think you'll need to use something like the [Proxy-Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization) header.

**Comment by xsgb** [comment]
Sure, HTTP basic auth for httpd. I may be noobishly-wrong but it seems passing "custom" headers actually requires changes in pynetbox.

**Comment by hSaria** [comment]
I'm 100% sure, but I don't think that would need a change on NetBox as the [`Proxy-Authorization`] header would be used for your proxy (httpd) and the existing `Authorization` field is used as is (gunicorn).

Basically, it's an extra header that you put into your request which httpd catches for itself, but you'd need to configure httpd for that.

**Comment by xsgb** [comment]
Yes, I've put my test application server behind HTTPBasic auth to test if I can reach it from our scripts.

True, NetBox itself have nothing to do with that. As I read in the [requests doc](https://2.python-requests.org/en/master/user/quickstart/#custom-headers), pynetbox would require to pass this custom headers to requests.get calls.

I've tried to get it working this afternoon, without much success ^^'

**Comment by hSaria** [comment]
Did you try to get it working purely using a `requests.Session`? https://github.com/digitalocean/pynetbox/pull/159 deal with additional headers; you should try to implement this on a fundamental level first (i.e. via `requests`) just to make sure it works.

**Comment by xsgb** [comment]
I should normally work but I tested, it does not because my httpd actually read the `Authorization` instead of `Proxy-Authentication` header to perform the Basic auth. So the requests contains only one `Authorization` key/value in the headers. I think that's the reason it does not work for me.

I've tried to use `Netbox-Authentication` as a name in netbox settings. Without success for the moment. 
https://github.com/netbox-community/netbox/blob/aff4ad0f9774856eff8a6fad906366899cb88209/netbox/netbox/settings.py#L457

**Comment by mmihir82** [comment]
Hi, @xsgb any luck with the BasicAuth. I'm trying same, with getting error: `{"detail":"Authentication credentials were not provided."}` Reason behind using the BasicAuth is to fetch all data based on devicename. `https://x.x.x/api/dcim/devices/?name=hostname`. Is there any other way to fetch data with IPaddress associate to that hostname? I tried `nb.dcim.get_devices(name="hostaname1")` but doesn't provide the content. Thanks

**Comment by zachmoody** [comment]
Closing this out since you _should_ be able to do basic auth now by passing a custom `requests.Session()` object.

**Comment by xsgb** [comment]
Oh, that's very neat. I'll try this. Thanks for this useful ability when running behind auth proxies.
