### ISSUE TITLE
pynetbox ssl validation should be configurable

### ISSUE THREAD

**Issue by explody** [digitalocean/pynetbox#21]
As TLS certs, particularly in test pipelines, may be generated from private CAs or self-signed, pynetbox should allow for _not_ verifying SSL certs, if explicitly set to do so.  The current behavior uses Requests' default, which is to require a valid cert and fail if it cannot be verified.

**Comment by Ichabond** [comment]
Requests allow you to export `REQUESTS_CA_BUNDLE` (http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification). This should fix the dev issue, without giving users a shotgun when it comes to security.

**Comment by explody** [comment]
Defaulting an available configuration to the preferred setting while still making it available for the user to override the behavior does not seem like much of a shotgun, IMHO.

Also, I don't believe this is equivalent function.  With access to build a bundle of CA certs, one could add them to the system bundle without requiring any specific config in the api client.

The use case we addressed is more of:  netbox instance is auto created with a self-signed cert as part of a pipeline while a client on a separate VM needs to access this transient instance over SSL.  The client never has direct access to the cert from which to build a bundle.  We could also just as easily remove SSL entirely or re-use a predictable cert, but neither is better practice IMHO. 

Besides, not verifying a server cert is really only a security issue when one does not control both ends of the connection and one has to trust _someone else_ ;)

**Comment by zachmoody** [comment]
Totally agree that every effort should be made to make your SSL infrastructure sane, but enforcing that  in an obscure python lib like this is seems like a bit of an overreach, imo.   :smile:

Dropped some comments in your PR, but overall I don't think it's a big deal to let the user toggle cert verification.
