### ISSUE TITLE
Getting the device id's of devices in a given rack

### ISSUE THREAD

**Issue by mohammedabdulmajid** [digitalocean/pynetbox#211]
Hello,
I understand this is not a bug, but more of feature request.
I have a requirement that i need to iterate rack by rack, get the devices in it and then update few fields.

I can get the device count and then iterate until the count of the devices using dcim/devices/{device_id}, but it will be really great if we can get the device id's of all the devices in a given rack so that i can avoid iterating all the devices from all the racks.

**Comment by shdxiang** [comment]
Similarly, I want to get a `circuit_termination` with a specified `cid`, seems `circuits.circuit_terminations.filter()` does not work for this. Did I miss something?

```json
 {
            "id": 1,
            "circuit": {
                "id": 1,
                "url": "http://netbox.spiral.exchange/api/circuits/circuits/1/",
                "cid": "123456"
            },
}
```

**Comment by zachmoody** [comment]
Closest I could think of is `devices.filter(rack_id=n)`. You'd need to know the rack_id, but that's easy enough if you nested it in something like
```
for rack in nb.dcim.racks.filter(**rack_search_terms):
  for device in nb.dcim.devices.filter(rack_id=rack.id):
    device.whatever = 'whatever'
    device.save()
```
