### ISSUE TITLE
Assigning vrfs with display_name to Prefixes and IP Addresses.

### ISSUE THREAD

**Issue by kerwbstomp** [digitalocean/pynetbox#217]
I suppose this is more of a feature request. 

I am trying to utilize Netbox's built in Custom Scripting functionality where a VRF that is already created is selected then passed on to be assigned to newly created Prefixes and IP Addresses. 
The problem that I am having is that the fields are populated with the standard dango querying such as VRF.objects.all(). This displays just the display_name field which includes the name and RD of said VRF. This is then passed down as an argument into the function but nb.ipam.vrfs.get()
does not seem to have a query based on display_name. I tried to work around it by altering the query to a values_list or value to just have the name i.e: VRF.objects.values_list('name, flat=True), but it seems that the Built in Custom Scripts models doesn't seem to allow that as a selection. All other things like tenant and so forth work fine.

When trying to examine the model with type it comes back as:
<class 'pynetbox.core.response.Record'> 
rather than:
 <class 'pynetbox.ipam.Prefixes'> like prefixes or the like.

I am leaning towards this is more of a netbox thing, when trying to view the dictionary or choices it also comes back with an object is not callable.
Here is an example:

get_vrf=nb.ipam.vrfs.get(name="Test Script VRF")
pprint(dict(get_vrf))
Traceback (most recent call last):
  File "vrf_model_query.py", line 14, in <module>
    pprint(dict(get_vrf))
TypeError: 'module' object is not callable

Is it possible to allow display_name as something I can query against? Forgive my ignorance if there is something I'm missing, I am rather new at python.

Thanks,

**Comment by zachmoody** [comment]
A little confused by the mention of custom scripts. Are you trying to use pynetbox in a NetBox custom script?

**Comment by kerwbstomp** [comment]
Yes, correct. In Netbox it is under Organization -> Misc -> Scripts. Also, I am getting the same results just using python in the CLI such as:

import pynetbox
import pprint
nb = pynetbox.api(url='http://localhost:80', token='redacted')

get_vrf=nb.ipam.vrfs.get(q="Test Script VRF")
pprint(dict(get_vrf))

**Comment by zachmoody** [comment]
What's the full traceback you get? That should work. *But* I would strong advise against using pynetbox in a custom script. The ORM is much more capable than pynetbox/REST api. Are you trying to get the form field in the script to display the VRFs `name` instead of its `display_name`?

**Comment by kerwbstomp** [comment]
Well the Prefixes and IPs build when executing the script, but since the vrf value that is passed is the 'display_name' it doesn't find query that matches, it builds everything with the null value for the vrf, so it just shows global.  All the other objects seem to work fine like Tenats.objects.all(), devices, prefixes,ip_addresses, etc. 

I also have tried to change to the formfield to display name instead of display_name but unfortunately it seems that netbox doesnt like that as an accepted selection.
 such as VRF.objects.values('name') it spits out the error 
'Select a valid choice. That choice is not one of the available choices.'

The idea is to assign Prefixes with Addresses, because more often than not users will only assign to global vrf or just the prefix or just the IP address, exclude descriptions, etc.

**Comment by zachmoody** [comment]
Hrm, yeah, maybe poke the netbox mailing list and see what they think. That sounds feasible. Either way, I don't think pynetbox will help you much here because, iirc, those fields are looking for QuerySets (might be why `.values()` doesn't work either) with model objects in them.

**Comment by kerwbstomp** [comment]
It's probably just me being terrible and new at python. I will deep dive more into django querying and the models. I much appreciate you taking a look at this thank you!.
