### ISSUE TITLE
When creating new Prefixes and IP Addresses, they will inherit the Parent Prefixes related VRF Object.

### ISSUE THREAD

**Issue by kerwbstomp** [digitalocean/pynetbox#218]
I suppose this would be a feature request?

I found out that when assigning available_prefixes or available_ips that the newly created objects only inherit the parent prefixes VRF assignment despite defining a different VRF.

I have a lot of VRFs and like to pull from the Global or 'null' prefixes in netbox and assign new addressing each time. I understand that you can have IP addresses and prefixes that overlap in separate routing domains but my use case helps those to never overlap by not checking global or whatever specific vrf. Is it possible to allow new vrf assignment if the vrf_id is defined?

IE:

import pynetbox
from netaddr import *
import pprint

nb = pynetbox.api(url='http://localhost:80', token='fbd8e2ea9f98b79c9d7e8634aa758ce3d1f957e2')

input_tenant = 25703
input_pfx = "172.28.77.0/24"
input_vrf = 2408
input_cidr = 31

pfx_dict = {
    "tenant": input_tenant,
    "vrf_id": input_vrf,
    "prefix_length": input_cidr,
    "description": "this is a test"

}
get_prefix = nb.ipam.prefixes.get(prefix=input_pfx)
new_prefix = get_prefix.available_prefixes.create(pfx_dict)

In order to get around this limitation you need to call the newly created object and update it.
example:

assign_vrf = nb.ipam.prefixes.get(prefix=new_prefix['prefix'])
assign_vrf.update({
    "vrf": input_vrf,
    })
assign_vrf.save()

Even though there is a work around, is it possible to add that feature if a vrf is explicitly defined?

**Comment by zachmoody** [comment]
I don't think pynetbox is the right place to add a feature like that. Maybe see if the NetBox folks are willing to accept a FR for a different VRF than parent on the available-prefixes endpoint.  Fwiw, `available_prefixes.create()` does return a `Prefixes` object now. So you should be able to skip the lookup and just do something like
```
new_prefix = get_prefix.available_prefixes.create(pfx_dict)
new_prefix.vrf = input_vrf
new_prefix.save()
```
