### ISSUE TITLE
Connection Error Exception on large filtered get

### ISSUE THREAD

**Issue by egreenspan2** [digitalocean/pynetbox#225]
Attempting to retrieve a relatively large number of netbox objects using filtered get, occasionally I get the following exception.

requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

Retrying operation will most of the time complete successfully.  Seems like the netbox server is taking longer to return the data which causes the timeout.

Traceback (most recent call last):
  File "<masked>/.venv/lib64/python3.6/site-packages/pynetbox/core/endpoint.py", line 225, in filter
    ret = [self._response_loader(i) for i in req.get()]
  File "<masked>/.venv/lib64/python3.6/site-packages/pynetbox/core/query.py", line 300, in get
    return req_all()
  File "<masked>/.venv/lib64/python3.6/site-packages/pynetbox/core/query.py", line 290, in req_all
    "offset": len(req["results"])
  File "<masked>/.venv/lib64/python3.6/site-packages/pynetbox/core/query.py", line 247, in _make_call
    params=params, json=data
  File "<masked>/.venv/lib64/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "<masked>/.venv/lib64/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "<masked>/.venv/lib64/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "<masked>/.venv/lib64/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by zachmoody** [comment]
Maybe lower `MAX_PAGE_SIZE` in NetBox and see if that helps. Pynetbox will paginate to whatever that's set to for responses that require it.

**Comment by egreenspan2** [comment]
> 
> 
> Maybe lower `MAX_PAGE_SIZE` in NetBox and see if that helps. Pynetbox will paginate to whatever that's set to for responses that require it.

Thank you for the suggestion, yes, it does appear to perform more consistently, now to figure out what value works best.  Clearly 1000 which is default is too much for it to handle sometimes.  I just can't figure out why it times out and closes the session in some cases and not others.  I can re-run the query a few seconds later and it completes.

**Comment by zachmoody** [comment]
Yeah that is strange, might want to play with how many workers you have and what your httpd and wsgi worker timeouts are. Tuning Django can be an art. :grimacing:

**Comment by egreenspan2** [comment]
> 
> 
> Yeah that is strange, might want to play with how many workers you have and what your httpd and wsgi worker timeouts are. Tuning Django can be an art. 😬

You bet, my first goto was to double the workers, I did not think about gunicorn timeout, it appears that the default value is 30s and I have been using the default Netbox systemd file which does not override it. 

However what are  your thoughts on keeping the page size relatively low (500 records?) and hope for feature request #191 to speed up paging with threading?

**Comment by zachmoody** [comment]
Yeah, that could help. Could always check out that branch and see. I haven't had chance to test it much, tbh.
