### ISSUE TITLE
Error 400 "1 is not a valid choice:

### ISSUE THREAD

**Issue by ognjen011** [digitalocean/pynetbox#226]
I seem to be getting this error:

pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'status': ['Select a valid choice. 1 is not one of the available choices.']}

When i try 

for host in netbox.dcim.devices.filter(manufacturer=brand,status=1):

I know that the API has changed on a Netbox end so that it is easier to use and we can now use Active instead of 1. But when i try Active

NameError: name 'Active' is not defined

I am running 2.7.9 version of Netbox and 4.2.5 version of pynetbox.

**Comment by mrfroggg** [comment]
Try with "active" as all values are in lowercase, labels can have uppercase, but your query search by value.

**Comment by ognjen011** [comment]
I tried that it didn't work. It's possible i am doing it wrong.

**Comment by zachmoody** [comment]
> NameError: name 'Active' is not defined

Means python is trying to find a variable named `Active` in your script. Make sure you're wrapping `"active"` with quotes.

**Comment by hashesdecoder** [comment]
@zachmoody I'm getting  a slimier  error: The request failed with code 400 Bad Request: {'site': ['Select a valid choice. xyz is not one of the available choices.']}
My code line: pprint(nb.dcim.devices.count(site="xyz"))
