### ISSUE TITLE
please allow overrides of requests.Session

### ISSUE THREAD

**Issue by daemonkeeper** [digitalocean/pynetbox#229]
I'd like to have the ability to override the default (requests) session object created in `Api.__init__()`, especially since the constructor immediately starts to make use of the requests Session object. Thing is, we run a custom setup requiring some non-standard attributes to be set to requests.Session, but there is no way to do by overriding `Api.http_session` before it's being used the first time in the constructor itself.

Current constructor is (relevant parts only)

```
class Api(object):
    def __init__(
        self,
        url,
        token=None,
        private_key=None,
        private_key_file=None,
        ssl_verify=True,
        threading=False,
    ):
...
        self.http_session = requests.Session()
...
        req = Request(
            base=base_url,
            token=token,
            private_key=private_key,
            ssl_verify=ssl_verify,
            http_session=self.http_session
        )
        if self.token and self.private_key:
            self.session_key = req.get_session_key()
...
```
Now thing is, Session has some attribtes that can be set, in my particular case a client cert I need to pass like so

````
s = requests.Session()
s.cert = ("cert", "key")
````

You do support `ssl_verify` which maps to requet's `verify` attribute. That too could be set through a session paramater. Therefore I suggest to rewrite `Api.__init__()` as follows

````
    def __init__(
        self,
        url,
        token=None,
        private_key=None,
        private_key_file=None,
        session=requests.Session(),
        threading=False,
    ):
        self.http_session = session
   
````

Then I as a user could do:

````
s = requests.Session()
s.cert = ("cert", "key")
s.verify = False
# whatever else one may want to tune and customize
nb = pynetbox.api(..., session=s)
````

If you remove `verify_ssl` this obviously breaks the API, but that could be easily worked around and kept for compatibility reasons, even without breaking existing code.

**Comment by daemonkeeper** [comment]
Oh and by the way, #189 deals with a similar problem, though that can be worked around otherwise. My suggestion would be a drive-by fix for #189 as well.

**Comment by zachmoody** [comment]
Yeah, #209 and #219 could probably benefit from it as well. Real blocker seems to be making the call to `.get_session_key()` key in init. I think that may make more sense in `App` when it's called for the secrets endpoint. That would at least let you set `api.http_session` universally after instantiation, but not opposed to letting it be passed as kwarg as well.

**Comment by daemonkeeper** [comment]
Absolutely. Session.auth allows basic authentication settings fixing #209, and Session.headers to add custom headers for #210, though that may need more care since you also set headers on a by-request basis, and I don't think requests.Session would merge them.

**Comment by zachmoody** [comment]
Done, opted not to make it a kwarg though, but we don't make any requests in `Api`'s init now.
