### ISSUE TITLE
Allow Providing the Exclude Config Context on Queries

### ISSUE THREAD

**Issue by newlandk** [digitalocean/pynetbox#230]
Are there any thoughts on how one could best implement the option to not generate configuration contexts when collecting devices (or other resources that support this query parameter)?

For example, a devices query supports the URL parameters of `?exclude=config_context`

https://github.com/netbox-community/netbox/blob/master/netbox/dcim/api/views.py#L386-L398

This greatly increases the performance of larger queries when provided during the request, and if you aren't using the configuration contexts from the query, there isn't really a need to have NetBox do the additional work.

Thanks!

**Comment by zachmoody** [comment]
kwargs for the `.get()` and `.filter()` method basically just get translated into url params. So e.g. `.filter(exclude="config_context")`, _should_ accomplish that.

**Comment by newlandk** [comment]
Oh, interesting @zachmoody I did not realize that was the case. I tested it and it works as expected. Thank you for the quick response.
