### ISSUE TITLE
Not getting all virtualization interfaces with all() with threading off

### ISSUE THREAD

**Issue by mnj** [digitalocean/pynetbox#231]
I got about 435 interfaces defined in Netbox (v2.7.9), using pynetbox 4.3.1

I can't put my finger on it, but all() returns 435 interfaces, but it does not contain a dozen or so interfaces that you get back when calling the REST API directly.

The weird thing is, they are all present on the REST API, and if I specify threading = True, it also returns what is expected, so seems like something is broken with the paging for the non threaded all() call.

a simple test case would be:

netbox_interfaces = netbox_client.virtualization.interfaces.all()
for nb_int in netbox_interfaces:
    print(f"Interface ID: {nb_int.id}, Virtual Machine ID: {nb_int.virtual_machine.id}")

You would expect it to return the same with threading on/off, but you get different results (when threading is on, it returns what is expected), attached output from running with and without threading.

But strangely they don't return the same, fx a VM with ID 1530 is only returned with threading = True

[threading-true.txt](https://github.com/digitalocean/pynetbox/files/4419481/threading-true.txt)
[threading-false.txt](https://github.com/digitalocean/pynetbox/files/4419482/threading-false.txt)

**Comment by markkuleinio** [comment]
@mnj Your **threading-false.txt** seems to miss some interfaces and contain some interfaces twice.

What are your `MAX_PAGE_SIZE` and `PAGINATE_COUNT` settings in NetBox?

My 2.7.11 installation only has some 400 prefixes (no interfaces), and they are returned identically with threading True and False. Also my 2.6.5 installation with about 1900 interfaces return identical lists both ways. Settings are `MAX_PAGE_SIZE = 1000` and `PAGINATE_COUNT = 200` in both.

```
>>> netbox.threading
False
>>> netbox2.threading
True
>>> ilist = netbox.dcim.interfaces.all()
>>> ilist2 = netbox2.dcim.interfaces.all()
>>> len(ilist)
1876
>>> len(ilist2)
1876
>>> ilist == ilist2
True
>>> pynetbox.__version__
'4.3.1'
>>>
```

**Comment by markkuleinio** [comment]
Btw there is a small discussion in https://groups.google.com/forum/#!topic/netbox-discuss/erKZYsabr5A about similar issue.

**Comment by markkuleinio** [comment]
@mnj Did you get anywhere with this? Restarting Redis has been solving some problems for users lately.

**Comment by mnj** [comment]
Sorry for the late reply, MAX_PAGE_SIZE is set to 0, PAGINATE_COUNT is set to 100.

I set up a development instance, using a daily export from our prod. database, it shows the same behavior, even after all services / caches are flushed.

I haven't spent any more time on this, since it works with the threaded call, just weird its inconsistent.

**Comment by markkuleinio** [comment]
Does the behaviour change if you set `MAX_PAGE_SIZE` back to the default of 1000?

**Comment by mnj** [comment]
I think you are right, it might have been redis, restarted everything once again, and now its working (and returning slightly fewer interfaces):

netbox_client1 = pynetbox.api (url=url, token=token, ssl_verify=False, threading=False)
netbox_client2 = pynetbox.api (url=url, token=token, ssl_verify=False, threading=True)

list1 = netbox_client1.virtualization.interfaces.all()
list2 = netbox_client2.virtualization.interfaces.all()

print(f"len(list1): { len(list1) } items")
print(f"len(list2): { len(list2) } items")
print(f"list1 == list2: {list1 == list2}")
print(f"pynetbox.__version__: {pynetbox.__version__}")

-->>

len(list1): 392 items
len(list2): 392 items
list1 == list2: True
pynetbox.__version__: 4.3.1

**Comment by markkuleinio** [comment]
Good to hear that, thanks for following up.
