### ISSUE TITLE
Question: how to filter on installed_device attribute from device_bays?

### ISSUE THREAD

**Issue by apallier** [digitalocean/pynetbox#235]
Hi, this is a question. I want to filter on `installed_device`  attribute from device_bays.

Here an example of what I want to do:

```python
api = pynetbox.api(address, token=token)
found = api.dcim.device_bays.filter(installed_device__name=device.name)
```

The previous code doesn't work as expected: I retrieve all device_bays (filter doesn't work).

Do you know a way to do that? Or should I filter after requested with "`.all()`" selector?

Thank you.

**Comment by zachmoody** [comment]
You're only able to pass valid filters as kwargs to `.filter()`. Have a look at the NetBox API docs for that endpoint to see what those are. Looks like `device=` might be what you're looking for.

**Comment by apallier** [comment]
I found the doc (https://netbox/api/docs/). I was not able to use `device` kwarg but `device_id` seems to work. Actually, it's the parent device of the bay and not the installed device in the bay.

My workaround is to filter after retrieve the whole list (with `all()`).

Let me known if you have an other idea.

Thank you.

**Comment by zachmoody** [comment]
Afraid I don't have any other ideas. I don't work with the `device_bay` endpoint all that much, but some endpoints do have more filters than others. Can't really think of another way to get around it, if that's the case.
