### ISSUE TITLE
Rack Units Change to Elevation

### ISSUE THREAD

**Issue by minitriga** [digitalocean/pynetbox#237]
I was testing my Slackbot out for units today and found out that the API endpoint has hanged. Needs to be Elevations.

https://github.com/netbox-community/netbox/releases/tag/v2.8.0

**Comment by DouglasHeriot** [comment]
Unrelated - I’m curious what your NetBox slack bot does - I’ve been thinking of building one.

**Comment by minitriga** [comment]
@DouglasHeriot 

https://youtu.be/6wl2suubMIQ?t=697

If you watch this video it shows NTC's slack bot. Mine is pretty much a replica of this. Doesn't have all the features yet. I built it to learn Slack API's. 

![image](https://user-images.githubusercontent.com/26367336/81909978-478ff700-95c3-11ea-955e-023117a3c37c.png)

**Comment by minitriga** [comment]
@zachmoody I have submitted a PR. Any chance you could have a look?

**Comment by zachmoody** [comment]
> @zachmoody I have submitted a PR. Any chance you could have a look?

I haven't, sorry about that, must have missed the notice. Looks good, added a couple comments that should be easy to resolve.
