### ISSUE TITLE
Add support for the dcim/_choices endpoint

### ISSUE THREAD

**Issue by Ichabond** [digitalocean/pynetbox#24]
Netbox has a `_choices` endpoint, which is currently not supported, as it gets remapped to `-choices` in `endpoint.py` (https://github.com/digitalocean/pynetbox/blob/master/pynetbox/lib/endpoint.py#L62), and it doesn't map to the default `Record` structure.

Update the application so it no longer remaps endpoints beginning with `_`, and add a specific class `Choice` that only has an `items()` function to retrieve the results.

**Comment by jord-bh** [comment]
@zachmoody any chance this will be bundled into pynetbox soon? I've solved this manually by the requests lib in my scripts for the time being, having it available straight through pynetbox would be sweet!

And obviously, while we're at it, having it available for all objects (dcim/virtualization/ipam/...) would be extra sweet.

**Comment by ebusto** [comment]
I'm also very interested in this!
