### ISSUE TITLE
Query Parameters

### ISSUE THREAD

**Issue by FragmentedPacket** [digitalocean/pynetbox#240]
Are we able to add a method to the `Request` object to fetch the available query_params from the Open API spec of NetBox?

URL: http://netbox/api/docs/?format=openapi" returns something along these lines:
```
openapi["paths"]["/dcim/devices/"]["get"]["parameters"]
```

This will help out in one of the projects I manage by validating query params passed in by users without much more client side logic.

**Comment by zachmoody** [comment]
Yeah that makes sense, long term goal is to eventually have a toggle to do validation against the openapi spec. So we'd need something in `Request` to build on anyways.
