### ISSUE TITLE
PyPI still only has pynetbox 4.3.1 instead of 4.3.2

### ISSUE THREAD

**Issue by markkuleinio** [digitalocean/pynetbox#244]
https://pypi.org/project/pynetbox/#history has 4.3.1, https://github.com/digitalocean/pynetbox/releases has 4.3.2.

**Comment by zachmoody** [comment]
Thanks for catching that, 4.3.3 should be on pypi now. Looks like Travis isn't reporting PR test results and I didn't notice some linting issues with the PR in 4.3.2 that kept the build from being published.
