### ISSUE TITLE
Add link to the Advanced page in the docs

### ISSUE THREAD

**Issue by markkuleinio** [digitalocean/pynetbox#258]
In #219 it is mentioned that page https://pynetbox.readthedocs.io/en/latest/advanced.html#headers has some documentation. Please add links to it in the docs, or is there a link somewhere? (I didn't notice while browsing the docs)

**Comment by zachmoody** [comment]
Aye, it's in the [API docstring](https://pynetbox.readthedocs.io/en/latest/#api) under `Additional Attributes -> http_session`. Didn't really want to make a table-of-contents entry for it, but if it gets missed regularly, we can.

**Comment by markkuleinio** [comment]
Right, got it, I guess it's right where it should be, for now at least.
