### ISSUE TITLE
Documentation Isn't Accurate

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/pynetbox#26]
I'm trying to use the examples from [pynetbox](http://pynetbox.readthedocs.io), but the examples are very inconsistent.

It appears to be a mixture of the API from NetBox v1.x and 2.x but I can't seem to make any sense out of it.  (See code under heading of `filter` at the URL `/en/latest/endpoint.html`) 

For example, I think that
> nb.devices.filter(role='leaf-switch')

should be

> nb.__dcim__.devices.filter(role='leaf-switch')

Also, I have a feeling that it __might__ be due to the release of `pynetbox v3.0.0` that caused this documentation error.  I'm wondering if it would be possbible to still be able to view the documentation for previous versions of `pynetbox` until this is resolved?

**Comment by zachmoody** [comment]
Sorry about that, thought I caught them all. Let me know if you see anymore.

**Comment by bdlamprecht** [comment]
Yeah, no worries, thanks for fixing that.

On a side note, am I incorrect in thinking that the documentation **used** to be more fleshed out than it is right now?  I thought I looked into this back in July sometime and was impressed with the available functionality but not in a position to attempt to use it then.  But now as I'm attempting to use the library, I see that the examples (for a newbie to python) aren't very understandable.

Also, I think I may have found a bug with `nb.ipam.prefixes.create` not handling passed `list` objects correctly, but not sure.  Should I open a new bug that or just post what I've come across on here?

**Comment by zachmoody** [comment]
I split them up into multiple pages in, I think, the 3.0.0 release. Before that it was just one big page, but they're still the same docs. They can certainly be better though. Let me know the places they're unclear and I'll see about fixing them.

As far as your issue with `.create()`, I started a thread on your mention of it in the NTC slack, but go ahead and open up a new issue and we can work it out there.

**Comment by bdlamprecht** [comment]
Yeah, I replied to your thread in the NTC slack channel. Thanks.
