### ISSUE TITLE
Missing or duplicated devices when threading is enabled

### ISSUE THREAD

**Issue by weisdd** [digitalocean/pynetbox#262]
While trying to improve the time it takes to pull info about 83 devices, I enabled threading (introduced in PR 216) and lowered the MAX_PAGE_SIZE to 20. It saved me a few seconds, though the results became inconsistent.

```python
#!/usr/bin/env python
import pynetbox
nb = pynetbox.api(
    "http://URL",
    token="TOKEN",
    threading=True,
)
print(len(nb.dcim.devices.filter(role=["switch", "router"], has_primary_ip=True)))
```
```bash
(venv) $ time ./temp_netbox.py
83
./temp_netbox.py  0,24s user 0,04s system 18% cpu 1,512 total
(venv) $ time ./temp_netbox.py
66
[...]
./temp_netbox.py  0,23s user 0,04s system 14% cpu 1,879 total
(venv) $ time ./temp_netbox.py
83
./temp_netbox.py  0,21s user 0,01s system 9% cpu 2,385 total
(venv) $ time ./temp_netbox.py
49
./temp_netbox.py  0,29s user 0,03s system 21% cpu 1,455 total
```

In the actual data I could see either a lot of duplicates or just missing devices.
The weird part is that sometimes it's every other request that gets affected, but could also be like dozens of normal results in a row.
Environment:
* pynetbox 4.3.3 / 5.0.1;
* CPython 3.8.2 on Ubuntu 20.04 / Nginx Unit 1.18 + python:3.7.7-slim-buster Docker image;
* netboxcommunity/netbox:v2.8.6-ldap / netboxcommunity/netbox:v2.8.7-ldap.

One more thing: I haven't seen the issue when calling nb.dcim.devices.all() (also with threading enabled and MAX_PAGE_SIZE of 20), so I currently assume it happens only with the nb.dcim.devices.filter().

Please, let me know if there's anything I could help you with to narrow it down.

UPD: I guess I should start with taking a traffic dump. Any advices on the Python side are appreciated :)

**Comment by markkuleinio** [comment]
Have you already restarted the server or at least Redis? In #231 that solved the similar problems.

Traffic dump would be useful yes, as you are using http, then you would get the exact URLs that the code is using. You can also check the web server logs for the requests.

**Comment by weisdd** [comment]
@markkuleinio In the beginning, I thought of possible caching issues, though crossed it off as it would make sense to me only in case of receiving the same results many times in a row. Traffic dumps were not at the top of my mind as I kind of left the networking a while ago. :) Anyway, when I looked at the dump, I saw that the issue seems to come from the requesting part:
![image](https://user-images.githubusercontent.com/46579601/86530155-0a5b2d80-bebf-11ea-828a-734b049dbfa6.png)
![image](https://user-images.githubusercontent.com/46579601/86530217-7d64a400-bebf-11ea-8681-39e8cc75718e.png)

It looks like there's something wrong in the queuing logic for concurrent futures.

**Comment by markkuleinio** [comment]
Thanks for the dumps, they really show that incorrect request offsets are the reason for incorrect output.

The code in `pynetbox/core/query.py` looks fine, the page offsets are generated like:

```
>>> pages = calc_pages(20, 83)
>>> pages
5
>>> page_offsets = [ increment * page_size for increment in range(1, pages) ]
>>> page_offsets
[20, 40, 60, 80]
```

but I see the same problem in both 4.3.1 and 5.0.1 (MAX_PAGE_SIZE = 10, with 41 devices). Not in every call but eventually.

**Comment by weisdd** [comment]
@markkuleinio I think I found the bug and a solution :) I'll open a PR soon :)

**Comment by markkuleinio** [comment]
In the venv with Pynetbox 5.0.1, I added this in line 256 (in `_make_call()`) in `query.py`:

`print(f"params = {params}")`

Then I did the threaded requests until failure occurred (first one was enough!), and there were the results (print outputs and the actual requests sent out):

```
>>> len(netbox.dcim.devices.filter(dummyfilter="xyz"))
params = {'dummyfilter': 'xyz', 'limit': 0}
params = {'dummyfilter': 'xyz', 'limit': 10, 'offset': 10}
params = {'dummyfilter': 'xyz', 'limit': 10, 'offset': 20}
params = {'dummyfilter': 'xyz', 'limit': 10, 'offset': 30}
params = {'dummyfilter': 'xyz', 'limit': 10, 'offset': 40}
41
>>>
```
```
"GET /api/dcim/devices/?dummyfilter=xyz&limit=0 HTTP/1.1" 200 12655 "-" "python-requests/2.24.0"
"GET /api/dcim/devices/?dummyfilter=xyz&limit=10&offset=40 HTTP/1.1" 200 1248 "-" "python-requests/2.24.0"
"GET /api/dcim/devices/?dummyfilter=xyz&limit=10&offset=20 HTTP/1.1" 200 12649 "-" "python-requests/2.24.0"
"GET /api/dcim/devices/?dummyfilter=xyz&limit=10&offset=20 HTTP/1.1" 200 12649 "-" "python-requests/2.24.0"
"GET /api/dcim/devices/?dummyfilter=xyz&limit=10&offset=30 HTTP/1.1" 200 12400 "-" "python-requests/2.24.0"
```

As you see, the `_make_call()` calls were made with correct offsets (10, 20, 30, 40) but the HTTP requests were made with offsets 20, 20, 30, 40.

**Comment by weisdd** [comment]
@markkuleinio That's right, I saw the same. I believe the issue is in _make_call:
```python
        params = {}
         if not url_override:
             if self.filters:
                 params = self.filters
```
I believe multiple calls are using the same attribute for filters, that's why we sometimes have collisions in concurrent calls. - It depends when a particular call starts.

**Comment by markkuleinio** [comment]
Looks like `requests.Session()` is not thread-safe: https://stackoverflow.com/questions/18188044/is-the-session-object-from-pythons-requests-library-thread-safe

This explains why `_make_call()` is clearly calling `.get()` with correct params but actual calls are incorrect.

**Comment by markkuleinio** [comment]
To recap what originally happened, thinking out aloud:

`params = self.filters` set `params` object to point to `self.filters` object, so `params` basically always point to the same memory location.

Then the next lines ("if `add_params` is present then update the `params` object (memory location) with the contents of `add_params` object") are executed nearly the same time in each threaded call, meaning that the actual `params` used in the GET call can be just about anything, as all the threads are updating the same memory location. And my prints were correct at the time of printing but not "correct" anymore at the time of GET call.

And the fix was to ensure that within each `_make_call()` call `params` always point to a separate object (which was created with `params = {}`), thus each GET call gets the correct `params`.

Was that the correct analysis of what happened?

**Comment by weisdd** [comment]
@markkuleinio That's exactly how my description should have looked like from the very beginning, - your wording is much better :+1: Thanks for taking the time! - I rarely get to "speak Python", just taking my first steps here :)

**Comment by tyler-8** [comment]
FWIW - I believe the `requests` `Session` object _can be_ safe if used properly; namely - the threads are not modifying the `Session` in any way - which is the case here with the NetBox API.
