### ISSUE TITLE
Bulk Edit to update multiple objects using pynetbox

### ISSUE THREAD

**Issue by pradiptama** [digitalocean/pynetbox#264]
Please direct me if I am missing any conversation or document. But is there any plan to add bulk edit to update multiple devices (or any other objects). Mostly I am expecting bulk edit will be faster operation than looping through multiple objects which is slow now. Current use case we have, we need to update many devices' status and the loop through operation is very slow.

**Comment by zachmoody** [comment]
I don't think the NetBox API supports bulk edit, feel free to reopen if I'm wrong.

**Comment by gdanielson** [comment]
https://github.com/netbox-community/netbox/pull/5166/
