### ISSUE TITLE
ssl_verify argument doesn't exist in 5.0.3 ?

### ISSUE THREAD

**Issue by victorh972** [digitalocean/pynetbox#265]
hello guys, i want to knows how ssl_verify exist before version 5.0.3 and not in the lastest version? and maybe you can explain me why some request works ans other's don't ?

cordially,
victor.

**Comment by zachmoody** [comment]
It was moved to custom user-defined request sessions. See [the docs](https://pynetbox.readthedocs.io/en/latest/advanced.html#ssl-verification) for some examples.

**Comment by victorh972** [comment]
thanks but it isn't solve the probleme  now time out and also the httpconnectionerror  wich talk about befor

**Comment by zachmoody** [comment]
Timeouts are configurable roughly the same way, examples are also in the docs. The connection errors are probably something else, can't really say without more info.

**Comment by victorh972** [comment]
in fact i want to execute that : nb.dcim.devices.all(). but time out and httpconnectionerror. however  for example that code : nb.ipam.prefixes.all() work. i don't knows more about that.

**Comment by zachmoody** [comment]
Sounds like it could be an issue with the combination of your `MAX_PAGE_SIZE`, WSGI worker timeouts, and device count. Can you make the same request with curl?

**Comment by victorh972** [comment]
i don't use curl but nb.dcim.devices.count() work

**Comment by markkuleinio** [comment]
Hi @victorh972, care to show your device count? If you like us to continue guessing one more time instead, you can try `nb.dcim.devices.filter(exclude="config_context")`. My guess is that you have a performance problem and you could try opening discussion in https://groups.google.com/g/netbox-discuss if you cannot solve it yourself and cannot afford paid support for NetBox.

Curl testing:
`curl -s -H "Accept: application/json" -H "Authorization: Token yourtokenhere" -X GET http://yournetboxserver/api/dcim/devices/`
