### ISSUE TITLE
Device Update: 405 Method Not Allowed

### ISSUE THREAD

**Issue by asergeant01** [digitalocean/pynetbox#267]
Netbox Version: v2.7.12
PyNetbox Version: 5.0.3
Python Version: 3.8.3

Test Script

```import pynetbox
api = pynetbox.api('http://netbox', token=load_netbox_token())
intf = api.dcim.interfaces.get(device='p17c09-mg-00', name='Ethernet51')
host = intf.cable.termination_a.device
host.status
# Returns Planned
host.status=1
host.save()
# Throws 405
```

This error seems to be due to commit https://github.com/digitalocean/pynetbox/commit/413695965c3abbc0e9ce6c79b85f0c45d95037c4

previously, inspecting the Record would show that self.url = http://netbox/api/dcim/devices/67/ and self.endpoint.url = http://netbox/api/dcim/devices/

therefore url would be passed through to the Request and the patch operation would succeed.

with the removal of base=self.url or self.endpoint.url, only endpoint is now passed through.

**Comment by asergeant01** [comment]
What is also a strange issue in the above example, if i remove the line host.status then when the record calls self._diff(), it isn't aware that a new status has been set.

```
api = pynetbox.api('http://netbox', token=load_netbox_token())
intf = api.dcim.interfaces.get(device='p17c09-mg-00', name='Ethernet51')
host = intf.cable.termination_a.device
host.status=1
host.save()
# Doesn't see a diff in the Record
```

**Comment by Dimaqa** [comment]
This also happens with DELETE for me

**Comment by markkuleinio** [comment]
#285 is maybe best for tracking the underlaying issue, if I understand correctly.
