### ISSUE TITLE
plugins api support

### ISSUE THREAD

**Issue by Pzharyuk** [digitalocean/pynetbox#268]
Will there be a plugins support with pynetbox?

**Comment by Dimaqa** [comment]
I believe that should be not hard to implement. Now you can use funny workaround:

**Comment by zachmoody** [comment]
No immediate plans for that. I haven't even had a chance to play around with any NetBox plugins. How do they tie into DRF?

**Comment by Dimaqa** [comment]
I think for most cases extend models with empty plugins is enough, because endpoints work just fine even now:
```
from pynetbox.core.endpoint import Endpoint
nb = pynetbox.api(url='url, token='token')
nb.http_session.verify = False
class Plugins:
    name = 'plugins'
p = Plugins()
pl = Endpoint(nb, p, 'plugin_url')
a = pl.filter(device_id=15)
print(a[0].__dict__)
```

**Comment by Dimaqa** [comment]
This should do #290
