### ISSUE TITLE
Pagination in get()

### ISSUE THREAD

**Issue by Dees7** [digitalocean/pynetbox#270]
Hello. 
I have a lot of device and if I do dcim.devices.all() it take very long time. 
I'd like to work with devices one by one. But I can't  find how to do this. In API we have limit and offset.
Is it possible using pagination with pynetbox 

pynetbox (4.3.1)

**Comment by tyler-8** [comment]
You could do something like this:

```python
devices = nb.dcim.devices.filter(brief=1)  # Very fast retrieval of device data

for device in devices:
    device.full_details()
    # Do things with the device Record object
```

**Comment by zachmoody** [comment]
Should be fixed in v6, `.all()` is a generator now you can step through pages as you iterate through results.
