### ISSUE TITLE
Cant create api instance with private key and ssl_verify=False

### ISSUE THREAD

**Issue by Dimaqa** [digitalocean/pynetbox#277]
From 5.0 release you need to specify http_session parameters after api initialisation.
But if you give private_key file to api, it will try to get session key from request on /api/secrets/get-session-key/?preserve_key=True, which will fail if you need to use ssl_verify=False.

```
nb = pynetbox.api('https://my_strange_netbox/', token=token, private_key=key)
Max retries exceeded with url: /api/secrets/get-session-key/?preserve_key=True
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))
```
You can probably make http_session as api.__init__ parameter to avoid it.

**Comment by zachmoody** [comment]
hrm, you sure you're using v5? The function to get the session key was moved from Api's init specifically because of this. It should only get the session key when you call something from `nb.secrets`.

**Comment by Dimaqa** [comment]
Hm.. 
My bad, it really works now, probably i misspelled http_session.verify with something like http_session.vevify in a first place
