### ISSUE TITLE
Regression: save() after create() no longer works - omits id from PATCH URL

### ISSUE THREAD

**Issue by candlerb** [digitalocean/pynetbox#285]
The following script works with pynetbox 4.0.8 but not with pynetbox 5.0.7

```
#!/usr/bin/python3
import pynetbox

name="test_1"
cluster="lxd"

nb = pynetbox.api('http://netbox.example.net',
        token='XXXXXXXX',
    )
vm = nb.virtualization.virtual_machines.create(dict(
        name=name,
        cluster={"name":cluster},
    ))
print(repr(vm))
print(vm.id)

vm.comments="testing"
vm.save()
```

With pynetbox 5.0.7 it gives the following output:

```
root@nuc1:~# python3 testapi.py
test_1
78
Traceback (most recent call last):
  File "testapi.py", line 18, in <module>
    vm.save()
  File "/usr/local/lib/python3.6/dist-packages/pynetbox/core/response.py", line 391, in save
    if req.patch({i: serialized[i] for i in diff}):
  File "/usr/local/lib/python3.6/dist-packages/pynetbox/core/query.py", line 409, in patch
    return self._make_call(verb="patch", data=data)
  File "/usr/local/lib/python3.6/dist-packages/pynetbox/core/query.py", line 274, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 405 Method Not Allowed: {'detail': 'Method "PATCH" not allowed.'}
```

tcpdump shows that it is trying to PATCH `/virtual-machines/` instead of `/virtual-machines/78/`

```
-->
PATCH /api/virtualization/virtual-machines/ HTTP/1.1
Host: netbox.example.net
User-Agent: python-requests/2.24.0
Accept-Encoding: gzip, deflate
accept: application/json;
Connection: keep-alive
authorization: Token XXXXXXXX
Content-Length: 23
Content-Type: application/json

{"comments": "testing"}

<--
HTTP/1.1 405 Method Not Allowed
Date: Sun, 23 Aug 2020 11:17:36 GMT
Server: gunicorn/20.0.4
Content-Type: application/json
Vary: Accept,Cookie,Origin
Allow: GET, POST, HEAD, OPTIONS
API-Version: 2.9
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
X-Frame-Options: SAMEORIGIN
Content-Length: 42
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive

{"detail":"Method \"PATCH\" not allowed."}
```

**Comment by ymasson** [comment]
Hi

Same error on Netbox v2.9.0.

Any workaround ?

**Comment by markkuleinio** [comment]
> Any workaround ?

1. Reorganize (optimize) your code so that you don't have to save your new object twice (i.e. add all the necessary properties in the `.create()` call)

2. Insert this before changing the newly created object:

`vm = nb.virtualization.virtual_machines.get(vm.id)`

HTH

**Comment by candlerb** [comment]
3. revert to an older version of pynetbox.  (I haven't done a binary chop to find where this was broken)

My real code cannot create all the attributes in a single call as suggested by @markkuleinio option 1.  It needs to create:

* A VM
* An interface attached to the VM
* IPv4 and IPv6 addresses attached to the interface
* Finally, set the VM primary IPv4 and IPv6 to point to those addresses

The Netbox API doesn't allow creating a tree of related objects in a single call, nor does it allow creating an interface which is not attached to anything.  Therefore I have to create the VM first, and then at the end patch it to set the primary IPv4 and IPv6.

**Comment by sylvain-garancher** [comment]
Hello,

I just hit this bug after updating Netbox to 2.9.

This seems to be caused by https://github.com/digitalocean/pynetbox/issues/285 as Netbox now sends `url` in GET.
This makes `key=self.id if not self.url else None,` to `key=None`.

**Comment by candlerb** [comment]
Thank you.  That commit was included in v4.2.4.  v4.2.3 was not published, so reverting to v4.2.2 or earlier should fix it.

Tested: v4.2.2 is happy.

**Comment by zachmoody** [comment]
Someone able to give `v5.0.8` a try and see if it fixes this? Otherwise I can test against a 2.9 instance later this week.

**Comment by sylvain-garancher** [comment]
This looks good to me, thanks.

Tested pynetbox `v5.0.8` on Netbox 2.8 and 2.9, my script is OK with both (creating/updating VMs, devices, interfaces and IP addresses).

**Comment by candlerb** [comment]
Works for me too, thanks!

**Comment by zachmoody** [comment]
Good to hear, thanks!
