### ISSUE TITLE
Change genes of client to be generative based on openapi specification

### ISSUE THREAD

**Issue by cherusk** [digitalocean/pynetbox#286]
Wondering, when this is the "**official**" digitalocean client, why it's not consuming the netbox openapi specification to generatively create the client as [1] there were references for that?

Only functionality to openapi I found is to dump the specification on cli as reference. :raised_eyebrow: 

[1] https://github.com/jeremyschulman/netbox-pyswagger

**Comment by zachmoody** [comment]
Historically, it's been because the openapi spec hasn't always been accurate. iirc, mostly around data types, which depending on how you're using the spec may or may not be a big deal. The plan is to do more with it, but probably not so far as generating a client solely on the spec.

**Comment by cherusk** [comment]
Hmm. Sounds askew for certain.

**Comment by cherusk** [comment]
:raised_eyebrow:

**Comment by cherusk** [comment]
> Historically, it's been because the openapi spec hasn't always been accurate. iirc, mostly around data types, which depending on how you're using the spec may or may not be a big deal.

Seriously, how's that possible? How can the spec and the consumption drift if it's maintained in one hand?

**Comment by cherusk** [comment]
Think have understood the point about data types, some are textual only, even the types, which makes tangible control hard. Closing hence.
