### ISSUE TITLE
REST API filtering doesn't work

### ISSUE THREAD

**Issue by szelga** [digitalocean/pynetbox#297]
when I query REST API, for instance, by `https://netbox.company.name/api/dcim/devices/?tags=12` URL, it shows all devices instead of just those with tag id 12.

Netbox 2.9.7, installed via docker-compose.

**Comment by markkuleinio** [comment]
`tags` is incorrect filter, correct is `tag`.

**Comment by szelga** [comment]
thanks. sorry, I posted it here, I honestly though I was posting to [netbox](https://github.com/netbox-community/netbox/). their API documentation is very bare-bones, so you'd have to look into netbox source code in order to perform filtering in pynetbox.

for future reference (to those who are confused as I was): https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/filters.py , class `DeviceFilterSet`.
