### ISSUE TITLE
duplicated ip addresses are discarded if threading is enabled

### ISSUE THREAD

**Issue by alegru** [digitalocean/pynetbox#298]
```
netbox = pynetbox.api(netbox_url, token=netbox_token, private_key_file=netbox_key_file, threading=True)
ip_mgmt_interfaces = {}
ip_all = netbox.ipam.ip_addresses.all()
for ip in ip_all:
    # workaround threading bug because of duplicates
    if ip.id in ip_mgmt_interfaces:
        dup_address = ip.address
        del ip_mgmt_interfaces[ip.id]
        dup_ips = netbox.ipam.ip_addresses.filter(address=dup_address)
        for ip in dup_ips:
            ip_mgmt_interfaces[ip.id] = (
                ip.assigned_object.name,
                ip.dns_name,
            )
        continue
    ip_mgmt_interfaces[ip.id] = (
        ip.assigned_object.name,
        ip.dns_name,
    )
```
Noticed if one has duplicate ip addresses, threading enabled and iterates over those addresses, the threadpool results aren't merged back correctly. If threading is disabled, every object has its correct id and all is well. But when threaded, the same ip object appears multiple times in the result instead of separate objects with their own id. See example above for the workaround I have to use to benefit from threaded requests.
I'm not sure if this is a general problem for other object types where duplications are allowed.
This is a problem in the latest pynetbox version (5.1.0 atm.) and NetBox v2.9.7

**Comment by markkuleinio** [comment]
I cannot confirm or repeat this on my setup. Can you be more specific and provide a minimum set of a repeatable error case?

Regarding the merging you mentioned, I don't see any merging in `pynetbox` threaded call code, just concatenating the result lists.

**Comment by tyler-8** [comment]
What is your MAX_PAGE_SIZE set to?

**Comment by tyler-8** [comment]
I'm seeing the same behavior on `pynetbox==5.1.0` and Netbox 2.8.X. I have a lot of duplicate IPs (intentionally, in different VRFs, sites, etc.)

```python
from collections import Counter

id_counts = Counter()

ip_all = nb.ipam.ip_addresses.all()

for ip in ip_all:
    id_counts[ip.id] += 1

dup_ids = [
    (ip_id, id_count)
    for ip_id, id_count in id_counts.items()
    if id_count > 1
]

print(len(dup_ids))
```

So something is happening in the way `pynetbox` is converting the JSON into Python objects that's going screwy when the threading is enabled.

**Comment by tyler-8** [comment]
Hmm... further testing required. I'm getting duplicate IDs without threading as well.

**Comment by tyler-8** [comment]
Okay I did the same query just using `requests` without `pynetbox` and still getting duplicate IDs. I suspect this is a NetBox bug but would like someone else to confirm.

**Comment by tyler-8** [comment]
I went ahead and tested it in a clean v2.9.9 install and found the same result. Threading isn't the issue here. Bug opened on the NetBox repo: https://github.com/netbox-community/netbox/issues/5345

**Comment by tyler-8** [comment]
Fix has been implemented in [NetBox](https://github.com/netbox-community/netbox/commit/9f8f9e8b97e2b42221000afe74619d25cb698b87) repo.

**Comment by alegru** [comment]
@tyler-8 Thank you for your help finding the root of the issue.
