### ISSUE TITLE
Users model not supported in current pynetbox yet

### ISSUE THREAD

**Issue by chiachoonloo** [digitalocean/pynetbox#299]
from v2.9 onwards, Netbox has added API support for Users/Groups/Permissions.
However this is not supported by current pynetbox yet.

Can we provide support for this so we can manage admin/users via pynetbox ?

`HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "groups": "http://localhost:8000/api/users/groups/",
    "permissions": "http://localhost:8000/api/users/permissions/",
    "users": "http://localhost:8000/api/users/users/"
}`

**Comment by markkuleinio** [comment]
@zachmoody is having hard time following all my pull requests 😂 but feel free @chiachoonloo to try my additions separately if desired.
