### ISSUE TITLE
Filtering manufacturers by 'id' doesn't seem to work properly.

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/pynetbox#30]
So, I'm trying to get the following NetBox call to work, but no matter which `id` I pass, I always get a list of all manufacturers back:
```
$ cat import_manufacturers.py
#!/usr/bin/env python

import pynetbox

url   = '[REMOVED]'
token = '[REMOVED]'
nb = pynetbox.api(url,token)

def manufacturer_details(id):
  print(nb.dcim.manufacturers.filter(id=id))

for i in range(1,7):
  print("ID: {}".format(i))
  manufacturer_details(1)
```

This **should** work, but all I get back is the following:
```
$ ./import_manufacturers.py
ID: 1
[APC, Arista, Cisco, Dell, HP, IBM, Juniper]
ID: 2
[APC, Arista, Cisco, Dell, HP, IBM, Juniper]
ID: 3
[APC, Arista, Cisco, Dell, HP, IBM, Juniper]
ID: 4
[APC, Arista, Cisco, Dell, HP, IBM, Juniper]
ID: 5
[APC, Arista, Cisco, Dell, HP, IBM, Juniper]
ID: 6
[APC, Arista, Cisco, Dell, HP, IBM, Juniper]
```

Filtering by `name` and `slug` both seem to work fine, it is just when using `id` it always returns a list of all existing `manufacturers`.

Running the same query via the API doesn't seem have this problem.

Any suggestions on what I'm doing incorrectly?

**Comment by zachmoody** [comment]
Returning all entries is default behavior in NetBox when you try passing a filter that doesn't exist. As you discovered, `name` and `slug` both work because they're the only fields setup to filter on [here](https://github.com/digitalocean/netbox/blob/develop/netbox/dcim/filters.py#L237-L241).

**Comment by bdlamprecht** [comment]
Well, that **_would_** make sense that the function returns everything if it doesn't understand the filter being used.

When I used `.get()`, everything worked like I expected it to, thanks for following up.
