### ISSUE TITLE
Updating devices with primary_ipv4 

### ISSUE THREAD

**Issue by jawyoonis** [digitalocean/pynetbox#300]
_**Goal:**_ I am trying to update the devices with primary_ipv4 but I am not seeing changes or issue
_**Code:**_ 
 `for iface, ipaddr in self.ip_interface_map.items(): `
                         `devices= self.nb.dcim.devices.get(iface.device.id)`
                         `devices.update(dict(primary_ipv4=ipaddr))`
************************************************************************************************************************

**I am accessing devices via interfaces and i am trying to assign primary_ipv4 to each device. The ips are currently associated with the interfaces.** 
***********************************************************************************************************************************
Version of Pynetbox: **5.1.0**
Netbox version: **2.9.4**

**Comment by markkuleinio** [comment]
In my test instance API does not show `primary_ipv4` for a device but `primary_ip4`, so you need to check that.

**Comment by jawyoonis** [comment]
wow! i did not realize that was my problem. Thanks @markkuleinio
