### ISSUE TITLE
Record attrs change even if save fails

### ISSUE THREAD

**Issue by Dimaqa** [digitalocean/pynetbox#301]
In current implementation if update request fails, record class instance will still change his attrs.

For example:

```
dev = nb.dcim.get(1)
try:
   dev.update({'name' : 'duplicated_name'})
except RequestError as e:
   print(dev.name)
```
will return 'duplicated_name'

This could be easy fixed by changing update() code from:
```
for k, v in data.items():
    setattr(self, k, v)
return self.save()
```
To something like

```
if self.save():
    for k, v in data.items():
        setattr(self, k, v)
    return True
return False
```

**Comment by zachmoody** [comment]
> To something like
> 
> ```
> if self.save():
>     for k, v in data.items():
>         setattr(self, k, v)
>     return True
> return False
> ```

Would it? Aren't you calling `.save()` before setting the information you're trying to update? I think I'd rather leave this to the client to handle instead of implementing some kind consistency feature. Not that it wouldn't be nice to have on `.update()` but then what about `.save()`.

**Comment by Dimaqa** [comment]
Yes it would, because `.save()` doesn't change pynetbox object, `settattr` does.

**Comment by zachmoody** [comment]
But what is `.save()` acting on if not what's provided in `data`?

**Comment by Dimaqa** [comment]
`Record.save()` sends PATCH request to Netbox. 
`Record.update()` updates pynetbox Record object and sends PATCH request to Netbox with new parameters. If this request fails, Record object would have new parameters anyway.

**Comment by zachmoody** [comment]
Update's just a convenience method around save() though. If you call save without setting the attributes, none of the changes you passed in data are going to get sent to NetBox.

**Comment by Dimaqa** [comment]
I guess you are right, there is no need to change something.
Thank you!
