### ISSUE TITLE
Wrong URL with Response on plugins Endpoint.

### ISSUE THREAD

**Issue by Thetacz** [digitalocean/pynetbox#302]
When using pynetbox with plugins, only creating a listing works. When I want for example deletion, pynetbox uses the wrong URL.

The underlying issue lies in having `url` set in GET serializer. If it's there, `Record.__init__` does not return endpoint directly but instead tries to return endpoint from gettattr(App, name), which returns new endpoint with wrong URL.
```
        self.endpoint = (
            self._endpoint_from_url(values["url"])
            if values and "url" in values
            else endpoint
        )
```
```
    def _endpoint_from_url(self, url):
        app, name = urlsplit(url).path.split("/")[2:4]
        return getattr(pynetbox.core.app.App(self.api, app), name)
```
This whole new Endpoint does not expect it to be plugin endpoint so it fails to get the correct URL. Instead of `http://127.0.0.1/api/plugins/ip_health_check/check/7` it tries to use `http://127.0.0.1/api/plugins/ip-health-check/7/`.

There is a nasty workaround though, manually changing internal endpoint.base_url:
```     
        response = nb.plugins.ip_health_check.check.filter(ip=ip.id)[0]
        response.endpoint.url = response.endpoint.base_url + "/plugins/ip_health_check/check"
        response.update({"result": True})
        response.delete()
```

The fix though seems really easy once I know all this, just avoid getting new endpoint when working with plugins. Will submit PR shortly.

**Comment by Dimaqa** [comment]
Hello!
For me it works fine. Could be something with your api implementation.
>>> nb.plugins.netbox_device_resources_plugin.devices.get(1407).delete()
True
>>> nb.plugins.netbox_device_resources_plugin.devices.get(1407)
None

**Comment by Thetacz** [comment]
Hello! Thanks for the reply.
Do you have `url` field in your GET serializer? If not, it works for me too, but if I add it (the same way core netbox does), it breaks it all. So you are correct, I have something in my api implementation - `url` field :)

This is the complicated line, just replace plugin and model name:
`url = serializers.HyperlinkedIdentityField(view_name="plugins-api:PLUGIN_NAME-api:MODEL_NAME_LOWERCASE-detail")`

Though I think you could reproduce it with anything in the `url` field as long as it is served in `fields()` set, that way you hit the `'url' in values` part of the condition and endpoint gets calculated from the url instead of returned directly. This line has the condition: https://github.com/digitalocean/pynetbox/blob/master/pynetbox/core/response.py#L174

**Comment by Dimaqa** [comment]
Oh, you are right. My bad

**Comment by markkuleinio** [comment]
@zachmoody Should we change `_endpoint_from_url()` to change behaviour if it detects `/plugins` in the URL? Or what would be a realistic fix for the URL parsing? I don't have experience about using plugins so I miss the relevant viewpoints on this.

`_endpoint_from_url()` has already been changed after this issue has been created, so its original snippet is not the current one anymore.

**Comment by Dimaqa** [comment]
Couldn't we just fix base_url in PluginsApp to `netbox/api/plugins` instead of `netbox/api`?

So <a href='https://github.com/digitalocean/pynetbox/blob/master/pynetbox/core/app.py#L148' >here</a> we just do:

    def __init__(self, api):
        self.api = api
        self.api.base_url =  "{}/plugins".format(self.api.base_url)

**Comment by markkuleinio** [comment]
I don't like changing the API base URL so #324 is a PR to try to solve this: it just makes `Record._endpoint_from_url()` to skip `plugins/` from the URL if present just after `api/`. Not tested with any actual plugins though.

**Comment by Dimaqa** [comment]
I think changing `base_url` is the better way of implementing plugins in the first place. We should not treat plugins endpoints  and base netbox endpoints differently, when we can just split api to _base-api_ and _plugins-api_ same way as netbox does it.
Since we already have #324 and #303, i won't create one more PR ;) Let's see what @zachmoody thinks about this...

**Comment by zachmoody** [comment]
> Could we just fix base_url in PluginsApp to `netbox/api/plugins` instead of `netbox/api`?
> 
> So [here](https://github.com/digitalocean/pynetbox/blob/master/pynetbox/core/app.py#L148) we just do:
> 
> ```
> def __init__(self, api):
>     self.api = api
>     self.api.base_url =  "{}/plugins".format(self.api.base_url)
> 
>  def __getattr__(self, name):
>     return App(self.api, name) # won't need /plugins anymore
> ```

It looks like the problem with this approach is `PluginsApp` is called in Api's init which results in base_url getting `/plugins` in all cases. Second thought was to try and only change when a `plugins` object's attribute was accessed. Which would seem to work, but that'd result in the base_url being permanently changed and subsequent calls from other apps would likely fail. Moral of the story is it's probably not a great idea to modify API attributes from other objects. :smile:  

#324 is probably the way to go since it has tests. @Thetacz Are you able to test that PR and verify it fixes your problem?

**Comment by Thetacz** [comment]
@zachmoody I tested the PR #324 and it fixes the issue. Thanks

Though this way of fixing it expects any plugin author to use the `url` the same way netbox does, which I don't think is guaranteed. This basically makes the `url` field reserved similar to how `id` is reserved. If someone chooses to use it for anything else, the object url will be wrong again. My change does not use the `url` field for url calculation, instead it takes directly the given endpoint. But I might have missed something to take into consideration as I hardly know the codebase. Feel free to take any path you like, both mentioned here fix the issue for me.

Note: The original issue was with 5.1.0, but I tested with 5.1.1 (the version @markkuleinio used as base) and newest 5.3.0, both reproduced the issue for me.

**Comment by zachmoody** [comment]
> Though this way of fixing it expects any plugin author to use the `url` the same way netbox does, which I don't think is guaranteed.

I mean, at some point, a plugin stops being an extension of NetBox and becomes its own thing. We can't support everything someone can do in a plugin. Though, it seems, both approaches presume `url` is a link to something served from netbox. Both operate on the `values['url']` entry, unless I'm missing something.
