### ISSUE TITLE
API .save() calls Fail when API host is in the format host:port

### ISSUE THREAD

**Issue by craized** [digitalocean/pynetbox#309]
When instantiating pynetbox API with a URL in the format host:port, as below, base_url gets set to http://host:port, but objects returned from the API do not include the :port designation. This is causing truncation of endpoint URLs when calling _endpoint_from_url in response.py

```
nb = pynetbox.api(
    host='localhost:80',
    'token'=mytoken
)
```

`device = nb.dcim.device.get(1)`

device.url will be "http://localhost/api/dcim/devices/1/"
base_url will be "http://localhost:80/api"

Calling `device.save()`

endpoint URL becomes:
im/device instead of dcim/device

**Comment by markkuleinio** [comment]
I can confirm this. Immediate workaround is to **not** include port 80 with the http URL when creating your `nb` object.

**Comment by zachmoody** [comment]
> Immediate workaround is to **not** include port 80 with the http URL when creating your `nb` object.

It's not just a workaround, it's RFC-compliant. :smile: 

[RFC3986](https://tools.ietf.org/html/rfc3986#section-3.2.3)
```
   URI producers and normalizers should omit the port component and its ":" delimiter if
   port is empty or if its value would be the same as that of the
   scheme's default.
```

**Comment by thecompletenoob** [comment]
Hi kinda new to this, 
I was trying to update in ip address in my lab when I realized it fails whether I use http://ipaddr or http://ipaddr:port and thought you should know
![image](https://user-images.githubusercontent.com/65258799/103326201-1f1c1680-4a47-11eb-801c-863c41058a43.png)
![image](https://user-images.githubusercontent.com/65258799/103326272-7326fb00-4a47-11eb-8055-a2400a3e5d6d.png)

**Comment by markkuleinio** [comment]
@thecompletenoob Please state your `pynetbox` version and give us full sample code to demonstrate the error.

**Comment by thecompletenoob** [comment]
@markkuleinio the pynetbox==5.2.0. I was on 5.1.2 before I upgraded. 

Please find the code I used below:

> 		import pynetbox
>
> 		netboxUrl = 'http://10.92.105.252'
> 		### netboxUrl = 'http://10.92.105.252:84'
> 		token = 'mytoken'
> 		
> 		nb = pynetbox.api(url=netboxUrl, token=token)
> 		
>		ipList = ['10.100.189.16/24', '10.100.189.17/24', '10.100.189.8/24']
>		for ip in ipList:
>		    ipAddr = nb.ipam.ip_addresses.get(q=ip)
>		    ipAddrUpdate = {
>		        'tenant': 10
>		    }
>		    try:
>		        ipAddr.update(ipAddrUpdate)
>		    except pynetbox.RequestError as e:
>	            print(f"\nCould not update the ip, error: {str(e)}\n")

**Comment by markkuleinio** [comment]
With NetBox 2.10.2 and `pynetbox` 5.2.0 here:

```
>>> nb = pynetbox.api(url="http://192.168.7.9", token="xxx")
>>> nb.ipam.ip_addresses.create({"address":"192.168.1.1/24"})
192.168.1.1/24
>>> nb.tenancy.tenants.create({"name":"Test", "slug":"test"})
Test
>>> ip = nb.ipam.ip_addresses.get(q="192.168.1.1/24")
>>> ip
192.168.1.1/24
>>> tenant = nb.tenancy.tenants.get(name="Test")
>>> tenant.id
2
>>> ip.update({"tenant": 2})
True
>>>
```

In the logs:

```
192.168.2.222 - - [30/Dec/2020:12:20:18 +0200] "POST /api/ipam/ip-addresses/ HTTP/1.1" 201 452 "-" "python-requests/2.25.0"
192.168.2.222 - - [30/Dec/2020:12:20:39 +0200] "POST /api/tenancy/tenants/ HTTP/1.1" 201 232 "-" "python-requests/2.25.0"
192.168.2.222 - - [30/Dec/2020:12:21:03 +0200] "GET /api/ipam/ip-addresses/?q=192.168.1.1%2F24 HTTP/1.1" 200 504 "-" "python-requests/2.25.0"
192.168.2.222 - - [30/Dec/2020:12:21:31 +0200] "GET /api/tenancy/tenants/?name=Test HTTP/1.1" 200 440 "-" "python-requests/2.25.0"
192.168.2.222 - - [30/Dec/2020:12:21:44 +0200] "PATCH /api/ipam/ip-addresses/1/ HTTP/1.1" 200 534 "-" "python-requests/2.25.0"
```

Works here, so more investigations are needed. I would recommend you open a new issue for your case and describe your http setup as well, are other operations failing as well, etc.

**Comment by thecompletenoob** [comment]
Thanks for your time. I forgot to add I'm on netbox 2.10.2
I also realized pynetbox works as it should when when I use "http://localhost" on the server itself when instantiating. Anything other than that fails. I will open a new issue with more details

**Comment by raddessi** [comment]
Shouldn't this work now that https://github.com/digitalocean/pynetbox/pull/323 was merged?

**Comment by zachmoody** [comment]
I think so, yeah.

**Comment by craized** [comment]
Thank you!
