### ISSUE TITLE
API .update() fails when API host is in the format "http://ipaddress". Endpoint API URL has missing characters

### ISSUE THREAD

**Issue by thecompletenoob** [digitalocean/pynetbox#322]
In reference to Issue #309 .update() still fails for me when I instantiate the api with "http://ipaddress".
 @markkuleinio suggested I raise a new issue with more information.
The only thing that works for me is "http://localhost" or "http://127.0.0.1" which I can't explain why.

My setup is:
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-128-generic x86_64)
nginx version: nginx/1.14.0 (Ubuntu)
Netbox v2.10.2
pynetbox==5.2.1
requests==2.25.1
six==1.11.0

This is the sample code I used:
>		import pynetbox
>		
>		netboxUrl = 'http://10.92.105.252'
>		token = 'mytoken'
>		
>		nb = pynetbox.api(url=netboxUrl, token=token)
>		
>		ipNew = nb.ipam.ip_addresses.create({"address": "192.168.7.1/24"})
>		
>		tenantNew = nb.tenancy.tenants.create({"name":"Test", "slug":"test"})
>		
>		ip = nb.ipam.ip_addresses.get(q="192.168.7.1/24")
>		
>		tenant = nb.tenancy.tenants.get(name="Test")
>		
>		try:
>		    ip.update({"tenant":tenant.id})
>		except pynetbox.RequestError as e:
>		    print(f"\nCould not update the ip, error: {str(e)}\n")
>

This is the error with the missing characters in the URL:
>		Could not update the ip, error: The requested url: http://10.92.105.252/api/m/ip-addresses/922/ could not be found.

Similar error for similar code but with the dcim/sites api:
>		Could not update the site, error: The requested url: http://10.92.105.252/api/m/sites/16/ could not be found.

I also realized that when i used a 192.168.1.5 during instantiation, the number of missing characters had reduced.
>		Could not update the ip, error: The requested url: http://192.168.1.5/api/pam/ip-addresses/189/ could not be found.

Kindly lemme know if more information is needed. Thanks for the support.

**Comment by markkuleinio** [comment]
What does `ip.url` show?

What is your nginx configuration?

What is your Python version?

**Comment by thecompletenoob** [comment]
@markkuleinio 
ip.url
>             ip.url: http://localhost/api/ipam/ip-addresses/923/

Python 3.6.9

nginx configuration:
>		server {
>		    listen 80;
>		
>		    server_name localhost;
>		
>		    client_max_body_size 25m;
>		
>		    location /static/ {
>		        alias /opt/netbox/netbox/static/;
>		    }
>		
>		    location / {
>		        proxy_pass http://127.0.0.1:8001;
>		        proxy_set_header X-Forwarded-Host $server_name;
>		        proxy_set_header X-Real-IP $remote_addr;
>		        proxy_set_header X-Forwarded-Proto $scheme;
>		        add_header P3P 'CP="ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"';
>	    }
>	}

**Comment by markkuleinio** [comment]
That configuration is not from your error case, your error case was the server with IP 10.92.105.252, not localhost

**Comment by thecompletenoob** [comment]
That's the server (10.92.105.252) nginx configuration. Are you suggesting i change the server name?

**Comment by markkuleinio** [comment]
Ok then that's your problem: your nginx (or NetBox) rewrites your URLs to localhost when you used the server IP in the NetBox API URL.

Use your server's correct URL when instantiating your `nb` object.

**Comment by markkuleinio** [comment]
(I don't know though how your 10.92.105.252:84 URL was working with this configuration at all... maybe you changed the configuration after your earlier report)

**Comment by thecompletenoob** [comment]
> Ok then that's your problem: your nginx (or NetBox) rewrites your URLs to localhost when you used the server IP in the NetBox API URL.
> 
> Use your server's correct URL when instantiating your `nb` object.

After changing the server name to the 10.92.105.252, .update() works. Tried it in different codes. I can use .update() from a remote computer.
Thanks a lot

**Comment by markkuleinio** [comment]
Thanks for the confirmation.

@zachmoody: I don't like this current situation with `Record._endpoint_from_url()` so expect some PR in the nearby days 😄 My idea is to skip the server:port part in both `base_url` and the argument URL, remove possible extra path from both of them, and then extract the `app` and `name` components of the path.

**Comment by thecompletenoob** [comment]
> (I don't know though how your 10.92.105.252:84 URL was working with this configuration at all... maybe you changed the configuration after your earlier report)

So I was using the port 84 for netbox instead of 80 with servername localhost in the same nginx config because i had another service running on 80 in the lab.  Using the 10.92.105.252:84 works with .get(), .filter() and .create() so far.

**Comment by thecompletenoob** [comment]
@markkuleinio I think the problem was with the nginx configuration. 

I changed this 
```proxy_set_header X-Forwarded-Host $server_name;``` to 
```proxy_set_header X-Forwarded-Host $http_host;``` and changed the server_name back to localhost.

Now my nginx configs look like this
```
server {
    listen 80;

    server_name localhost;

    client_max_body_size 25m;

    location /static/ {
        alias /opt/netbox/netbox/static/;
    }

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header P3P 'CP="ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"';
    }
}
```

So far this works for me and even works with "http://host:port". 

Thanks a lot
