### ISSUE TITLE
unable to add untagged_vlan to dcim.interface

### ISSUE THREAD

**Issue by barnebyte** [digitalocean/pynetbox#334]
Hey Guys,

I'm trying to add an existing vlan to an interface (to its untagged_vlan object which is None before executing the script), it looks like it's working, no error message from pynetbox and response code 200 in Netbox logs, but the interface is not updated in Netbox. The changelog is showing that the interface object has been updated but the Difference is empty.

This is my code (simplified):
```
interfaces = nb.dcim.interfaces.filter(device_id=1)
for ifc in interfaces:
    ifc.untagged_vlan = 1
    ifc.save()
```

I also tried with
`ifc.update({ "untagged_vlan" : { "id" : 1 } })`
but with the same result.

What am i missing?
I'm using Pynetbox 5.3.1 with Netbox 2.10.4 and Python 3.8.5

Thanks!

**Comment by markkuleinio** [comment]
What is your interface mode set to?

If your interface mode is `None`, the access VLAN is not selectable (just like in the GUI).

```
>>> i = netbox.dcim.interfaces.get(device_id=1)
>>> print(i.untagged_vlan)
None
>>> print(i.mode)
None
>>> i.mode = "access"
>>> i.save()
True
>>> i.untagged_vlan = 1
>>> i.save()
>>> i = netbox.dcim.interfaces.get(device_id=1)
>>> print(i.untagged_vlan)
Vlan111
>>>
```

**Comment by barnebyte** [comment]
OMG, thank you! I wasted so many hours on this. You are right, after setting the mode to access, the ungagged vlan can be saved.
Have a nice day!
