### ISSUE TITLE
Filter within FrontPort is not working

### ISSUE THREAD

**Issue by jcralbino** [digitalocean/pynetbox#340]
When running this:
nb = pynetbox.api('https://netboxip',token='sdsd')
frontport = nb.dcim.FrontPorts.filter(device_id=156)

We get this error 
RequestError: The requested url: https://netboxip/api/dcim/FrontPorts/?device_id=156 could not be found.

The correct url from
https://netboxip/api/docs/ 
is  
https://netboxip/api/dcim/front-ports/?device_id=156

I believe this is a bug in the pynetbox, can you confirm i am running pynetbox version 5.3.1

**Comment by markkuleinio** [comment]
So `dcim.FrontPorts` did not work, but did you try `dcim.front_ports` as implied by your investigations? (Dashes in the API URL need to be replaced by underscores to be usable in Python object names)
