### ISSUE TITLE
Support for custom-fields API released in netbox 2.10

### ISSUE THREAD

**Issue by jianan-pony** [digitalocean/pynetbox#347]
As mentioned in https://github.com/netbox-community/netbox/pull/5455 2.10 release, the custom-fields implementation and endpoints are updated to support more flexible API query pattern. However, the latest release of pynetbox seems still does not support it, as it only contains `_custom_field_choices` endpoint [here](https://github.com/digitalocean/pynetbox/blob/master/pynetbox/core/app.py#L107) instead of the new endpoint of `custom-fields`. Please help consider adding it. Thanks.

**Comment by markkuleinio** [comment]
Can you tell what kind of additional support from `pynetbox` are you looking for? Currently (with `pynetbox` 5.3.1) there is for example:

```
>>> netbox.version
'2.10'

>>> netbox.extras.custom_fields.all()
[dhcp_excludes]

>>> pprint(dict(netbox.extras.custom_fields.get(name="dhcp_excludes")))
{'choices': [],
 'content_types': ['ipam.prefix'],
 'default': None,
 'description': '',
 'filter_logic': {'label': 'Loose', 'value': 'loose'},
 'id': 1,
 'label': 'DHCP excludes',
 'name': 'dhcp_excludes',
 'required': False,
 'type': {'label': 'Text', 'value': 'text'},
 'url': 'http://netbox-test.lein.io/api/extras/custom-fields/1/',
 'validation_maximum': None,
 'validation_minimum': None,
 'validation_regex': '',
 'weight': 100}
```

**Comment by jianan-pony** [comment]
Seems I'm confused with the `custom_fields` with the `custom_field_choices` related implementation mentioned above. Tested and it worked fine. Thanks. Closed this issue.
