### ISSUE TITLE
Updating Config Context Fails

### ISSUE THREAD

**Issue by DCAuto** [digitalocean/pynetbox#349]
I have a somewhat complicated config_context of a series of nested-dicts/lists. Updating this fails, even when updating it to the same values.

Example:

Existing Config Context JSON
```
{
    "bgp_overlay": {
        "neighbors": [
            {
                "description": "Switch1",
                "ip": "10.10.10.1"
            },
            {
                "description": "Switch2",
                "ip": "10.10.10.2"
            }
        ]
    },
    "bgp_overlay_rr": {
        "neighbors": [
            {
                "description": "Switch3",
                "ip": "10.10.10.3"
            },
            {
                "description": "Switch4",
                "ip": "10.10.10.4"
            }
        ]
    }
}
```

when attempting to update and save I get the following:
```
>>> test = nb.extras.config_contexts.get(name='test_config')
>>> test.data['bgp_overlay']['neighbors'].append({'ip': '10.10.10.5', 'description': 'new_switch'})
>>> test.save()
False
```

even writing to the same value fails:
```
>>> test = nb.extras.config_contexts.get(name='test_config')
>>> holder = test.data
>>> test.data = holder
>>> test.save()
False
```

**Comment by DCAuto** [comment]
I believe I have found out the root issue. Pynetbox interprets "bgp_overlay" and "bgp_overlay_rr" as duplicate keys. Changing either of those keys allows a save. This does appear to be a bug in pynetbox, as if `.save()` returns `False` then it never sends a `PATCH` to the netbox server.

**Comment by zachmoody** [comment]
Think that was fixed in https://github.com/digitalocean/pynetbox/pull/266. What version of pynetbox are you using?

**Comment by DCAuto** [comment]
pynetbox==5.3.1

**Comment by DCAuto** [comment]
I think the issue is that #266 has an update for "local_config_data" and does not include "config_context" as well.

**Comment by zachmoody** [comment]
Ah gotcha, will look into it.
