### ISSUE TITLE
How to run tests without docker?

### ISSUE THREAD

**Issue by ignatenkobrain** [digitalocean/pynetbox#353]
Hello,

Fedora maintainer here. During upgrade to 6.x I noticed that many tests started to fail as they try to run docker.

I'm not very familiar with pytest infrastructure, so I would appreciate if you could help me to skip those tests.

**Comment by zachmoody** [comment]
Hey @ignatenkobrain, what's easiest for you? We'd originally planned that folks who wanted to skip the integration tests could do something like
```
pytest tests/test_*.py tests/unit
```
but we'd also considered a flag we pass to pytest to skip them as well.

Eventually we'll migrate all the `tests/test_*.py` to integration tests and you could do `pytest tests/unit` to effectively skip them.

**Comment by ignatenkobrain** [comment]
well, any option is easy for me as long as it works :)

**Comment by zachmoody** [comment]
haha, I hear you. The above should work for you then. Lmk if you need a cleaner way to do it.
