### ISSUE TITLE
Add support for deleting objects

### ISSUE THREAD

**Issue by Grokzen** [digitalocean/pynetbox#44]
I can't find any support for deleting objects on a endpoint. I found in the api docs for netbox itself that it is supported so it would be great if pynetbox would support this feature as well.

**Comment by zachmoody** [comment]
:wave: @Grokzen - we don't have a delete method that operates on an endpoint at the moment. I'd like to add one, along with update, but the only way to delete an object for now is the `.delete()` method off of `Record` objects talked about [here](http://pynetbox.readthedocs.io/en/latest/response.html#pynetbox.lib.response.Record.delete).

**Comment by Grokzen** [comment]
Ah, will try that one. Many thanks for quick response :]
