### ISSUE TITLE
Add support for NAPALM methods

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/pynetbox#45]
This could already exist, but as I was poking around, I didn't see the function call where I expected it would be.  Basically, I'm trying to use `pynetbox` to do something like the following REST API call:
```
curl -X GET -H "Accept: application/json; indent=2" -H "Authorization: Token [REMOVED]" "http://netbox.local/api/dcim/devices/20/napalm/?method=get_facts"
```
While poking around and doing a `dir(dev1)` in the python interpreter (where `dev1` has the`id=20` in the API call above) and all I saw was the following:
```
>>> dir(dev1)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__hash__', '__init__', '__iter__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_add_cache', '_compare', '_full_cache', '_index_cache', '_parse_values', 'api_kwargs', 'asset_tag', 'cluster', 'comments', 'created', 'custom_fields', 'default_ret', 'delete', 'device_role', 'device_type', 'display_name', 'endpoint_meta', 'face', 'full_details', 'has_details', 'id', 'last_updated', 'name', 'parent_device', 'platform', 'position', 'primary_ip', 'primary_ip4', 'primary_ip6', 'rack', 'save', 'serial', 'serialize', 'site', 'status', 'tenant', 'url', 'vc_position', 'vc_priority', 'virtual_chassis']
```

Anyways, I suppose my question boils down to the following...
1. Is `NAPALM` already supported?
2. If so, where should I be looking at (instead of the location above)?
3. If not, could I request that it be added in the near future?

Thanks again for this library (and `NetBox` too)!

**Comment by zachmoody** [comment]
I _think_ it'd just require statically defining a `DetailEndpoint()` on `Devices` like we do on `Prefixes` for available_ip's and prefixes. Should be pretty straightforward, I'll see if I can get to it this week.

**Comment by bdlamprecht** [comment]
That would be great!

**Comment by bdlamprecht** [comment]
@zachmoody 

Were you able to make any progress on this feature request at all or even started looking into it yet?
I appreciate any response that you can provide

Cheers,
Brady

**Comment by bdlamprecht** [comment]
This is exactly what I was looking for, thanks a lot.

PS - I really like the `model` you used of `UnobtaniumX` in the file `tests/fixtures/dcim/napalm.json`

**Comment by zachmoody** [comment]
yw! haha, tried to sneak that in there . 😄 NetBox has, or used to have, some good ones in its tests too.
