### ISSUE TITLE
List device_role and all other attributes of an endpoint

### ISSUE THREAD

**Issue by hpanago** [digitalocean/pynetbox#49]
I can see that there is no function that returns the "_attributes_" of an endpoint.

For example, with `nb.dcim.devices.all()`, I do get all the devices by their name.
But what if I need something more specific like `device_role`?

This is implemented only when _creating_ a device, where `device_role` is set, but after that I can not seem to be able to retrieve it somehow.

Am I correct? 

If yes, will this functionality be added?

My thought for this was, to use e.g. a "show_details" function/API call to get the device role (or any other of the "facts") and then use the nb.dcim.device.filter(role=<fact>) to get a dict with the specific role.

Thanks.

**Comment by zachmoody** [comment]
Not sure I completely follow, but `device_role` is just an attribute on each response returned by `devices.all()`. If you wanted to print name and device_role you'd just do something like this:

```
for i in nb.dcim.devices.all():
  print(i.name, i.device_role)
```
`i.device_role` is the same type of object as `i` with attributes of its own representing the nested response of device_roles from the devices endpoint. So if you wanted the device_role slug you could call it with `i.device_role.slug`. Hope that's what you were looking for.

**Comment by hpanago** [comment]
That is exactly what I was asking for!

Also thank you for the quick response. :+1:
