### ISSUE TITLE
Getting Error for Time Zone Required When Updating Site

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/pynetbox#59]
### Issue type
[X] Bug report      

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.3
* PyNetBox version: 3.3.0

### Description
When updating an existing `site` via the WebUI, the field `Time Zone` is not required (see screenshot A).
The same is true for using the SwaggerUI (see screenshot B for `patch` & C for `response`).

However, when you try the same thing using the `pynetbox` code:
```
nb_site.status = 1    
nb_site.description = "string"
nb_site.custom_fields['reso_id'] = bgp_comm

try:
    nb_site.save()
    nb_updated_sites.append(nb_site.name)
except pynetbox.lib.query.RequestError as e:
    print("Failed due to:\n    {}".format(e.error))
```
The following error is recieved:
```
Failed due to:
    {"time_zone":["This field may not be null."]}
```

When `time_zone` is **ADDED** to the code:
```
nb_site.status = 1    
nb_site.description = "string"
nb_site.custom_fields['reso_id'] = bgp_comm
nb_site.time_zone = 'UTC'

try:
    nb_site.save()
    nb_updated_sites.append(nb_site.name)
except pynetbox.lib.query.RequestError as e:
    print("Failed due to:\n    {}".format(e.error))
```

No errors are returned!

---
Screenshot A:
![image](https://user-images.githubusercontent.com/7783306/40941354-c9b85786-6807-11e8-8984-eb630c18aa96.png)

---
Screenshot B:
![image](https://user-images.githubusercontent.com/7783306/40941678-ded3620e-6808-11e8-8ee0-0b8e1630b3bd.png)

---
Screenshot C:
![image](https://user-images.githubusercontent.com/7783306/40941728-12b37758-6809-11e8-8001-869c5d09e0d5.png)

**Comment by zachmoody** [comment]
At first glance, I don't think this error's from pynetbox. It doesn't do any client-side validation so the type of error you're getting is from NetBox. Might want to try a simple test with curl using PUT (PATCH'ing isn't in pynetbox yet). Swagger says it's not required, but that error seems to indicate otherwise.

**Comment by bdlamprecht** [comment]
As you requested, I tried a `PUT` instead (I had to include the fields `name` and `slug` as I got errors otherwise):

![image](https://user-images.githubusercontent.com/7783306/40943772-9e0ef628-680f-11e8-90ae-ec4b11dbf706.png)

And it worked fine:
![image](https://user-images.githubusercontent.com/7783306/40943850-d4e76a7c-680f-11e8-88c2-3a78d0a10c68.png)

Since you said that `pynetbox` doesn't do any client-side validation, I'm not sure where the error about the `time_zone` is coming from.  Really strange.

**Comment by bdlamprecht** [comment]
I was going to ask if you had any updates on this yet, but I saw that `jeremystretch` just merged the fix in, so that's great.  I appreciate you looking into this and working to get it fixed.

Cheers!

**Comment by zachmoody** [comment]
Will close this issue out then since there's nothing we can do on the pynetbox side.
