### ISSUE TITLE
Cant't access ipam.ip-addresses is function name contains dash

### ISSUE THREAD

**Issue by oysteingy** [digitalocean/pynetbox#7]
Hi, 

Nice API, however I've run into a glitch. 
Most of the subcontent of ipam works as pr the documentation:

>>> import pynetbox
>>> nb = pynetbox.api('http://localhost:8080',token=token)
>>> nb.ipam.vrfs.all()
[customer1, customer2, cust3]
>>> nb.ipam.prefixes.all()
[10.219.60.0/24, 10.219.60.232/29, 100.0.0.0/24]
>>> nb.ipam.vlans.all()
[L2_PSEUDO_10000]

ip-addresses and vlan-groups does not work however, as Python will errornously interprent the dash.

>>> nb.ipam.ip-addresses.all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'addresses' is not defined
>>> nb.ipam.vlan-groups.all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'groups' is not defined

Got the API links from
https://github.com/digitalocean/netbox/blob/develop/netbox/ipam/urls.py

**Comment by zachmoody** [comment]
Hi @oysteingy, sorry about that, the docs mentioning this behavior must have gotten lost somewhere. But any endpoint with a dash is converted to an underscore in the API. E.g. `nb.ipam.ip_addresses.all()` should work. I'll make sure it gets added to the docs.

**Comment by oysteingy** [comment]
Thank you @zachmoody - that did indeed work.
