### ISSUE TITLE
Problem with all() and filter() methods for circuits

### ISSUE THREAD

**Issue by fr33l4ncer** [digitalocean/pynetbox#77]
circ = nb.circuits.circuits.filter(status=5)

retrurns 
[, , , , , , , , , , , , , , , , , , , , , , , ]

works with requests
log shows proper working call
"GET /api/circuits/circuits/?status=5 HTTP/1.1" 200 52

circ = nb.circuits.circuits.all()

returns
[,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ,
 ]
log shows proper working call
"GET /api/circuits/circuits/ HTTP/1.1" 200 516

I can get individual circuits by get() method no problem

**Comment by zachmoody** [comment]
This should've just been addressed in v3.4.4 - Is that what you're running?

**Comment by fr33l4ncer** [comment]
Was running 3.4.3 ;) I updated it today morning and didn't noticed there was another new one released  3h ago ;) 
It works as expected now , many thanks
