### ISSUE TITLE
How to use custom_fields in create()

### ISSUE THREAD

**Issue by s-takehana** [digitalocean/pynetbox#8]
Hi,

How to use custom_fields in [create()](http://pynetbox.readthedocs.io/en/latest/#pynetbox.lib.endpoint.Endpoint.create)?

Could you provide an example please?

**Comment by zachmoody** [comment]
You'd pass a dictionary to a named arg of `custom_fields`. There's an example in the tests here: https://github.com/digitalocean/pynetbox/blob/master/tests/test_dcim.py#L226-L231

That _should_ work.
