### ISSUE TITLE
Updating the 'site' Model causes an HTTP error, but correctly updates attributes anyways

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/pynetbox#80]
### Issue type
[X] Bug report      

### Environment
* Python version:  3.6
* NetBox version:  2.4-beta1
* PyNetBox version: 3.4.4

Although it is a beta-release that I'm testing against, I thought I would note it anyways as it has the potential to cause issues when the stable version is released.

When trying to update attributes to any `site` via `pynetbox` and performing a `nb_site.save()`, an HTML error is returned but the actual object in `NetBox` **_is_** updated correctly.

I've tried to single out which attribute is causing this error, but all of the ones I've tested (`description`, `physical_address`, `timezone`, `custom_fields`) appear to produce the same result:

```

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Server Error</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.min.css">
    <meta charset="UTF-8">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-danger" style="margin-top: 200px">
                    <div class="panel-heading">
                        <strong>
                            <i class="fa fa-warning"></i>
                            Server Error
                        </strong>
                    </div>
                    <div class="panel-body">

                            <p>
                                There was a problem with your request. Please contact an administrator.
                            </p>

                        <hr />
                        <p>
                            The complete exception is provided below:
                        </p>
<pre><strong></strong><br />
</pre>
                        <p>
                            If further assistance is required, please post to the <a href="https://groups.google.com/forum/#!forum/netbox-discuss">NetBox mailing list</a>.
                        </p>
                        <div class="text-right">
                            <a href="/" class="btn btn-primary">Home Page</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>
```

It _could_ be due to some changes in the core of `NetBox v2.4` that hasn't been updated in `pynetbox` just yet, however, the more time to investigate the better.

Let me know what other information you need to troubleshoot this issue.

**Comment by zachmoody** [comment]
Looks to have something to do with tags, best I can tell. Opened https://github.com/digitalocean/netbox/issues/2294 to see if we can get it sorted.

**Comment by bdlamprecht** [comment]
Much appreciated, thanks for looking into it.

As you said, "not sure of the consequences of this", we'll see what @jeremystretch has to say about it.
