### ISSUE TITLE
Updating primary ip on virtual machine doesn't work

### ISSUE THREAD

**Issue by gus4520** [digitalocean/pynetbox#84]
Whenever I try to update the primary_ip attribute, it doesn't return an error, but the field is also not updated. I have tried it by doing:

vmupdate = nb.virtualization.virtual_machines.get(name="vmname")
vmupdate.primary_ip = '10.0.0.1'
vmupdate.save

**Comment by zachmoody** [comment]
Haven't done a lot of work personally with the virtualization endpoint, but I think the field on POST is `.primary_ip<family>` and it's a key to an ip_address object not a string. Also, you're probably looking for `.save()`.

**Comment by gus4520** [comment]
Hi Zach,

Thanks for getting back to me. Definitely a typo on my part missing the (). I tried the following:

vmupdate = nb.virtualization.virtual_machines.get(name='vmname')
vmupdate.primary_ip4 = 2048
vmupdate.save()

This is the error that I get:

Traceback (most recent call last):
  File "./test_net.py", line 27, in <module>
    vmupdate.save()
  File "/usr/local/lib/python2.7/site-packages/pynetbox/lib/response.py", line 266, in save
    if req.put(self.serialize()):
  File "/usr/local/lib/python2.7/site-packages/pynetbox/lib/query.py", line 270, in put
    raise RequestError(req)
pynetbox.lib.query.RequestError: The request failed with code 400 Bad Request

2048 is the id associated with the IP address that I am trying to add to the specific VM. I can note that the option to add the IP address with the GUI goes as follows:

1) create VM
2) Add interface to VM
3) Add IP to interface and check the box to make the ip the primary interface

Do I need to reference the interface id in the API?

**Comment by zachmoody** [comment]
```
vmupdate = nb.virtualization.virtual_machines.get(name='vmname')
vmupdate.primary_ip4 = 2048
vmupdate.save()
```
hrm, yeah, that's the process on `devices`, which I think `virtual_machines` are very similar. You can get more details when a `RequestError` is raised if you catch and print the `error` attribute like so:

```
try:
  vmupdate.save()
except pynetbox.RequestError as e:
  print(e.error)
```

That might give you a better idea of what NetBox is unhappy about.
