### ISSUE TITLE
Can't lookup values for nested objects

### ISSUE THREAD

**Issue by oysteingy** [digitalocean/pynetbox#9]
Hi, 

Thanks for the very nice API. 

I've ran into some glict, I've reproduced this on two separate systems with pynetbox 2.0.5 and netbox 2.1.3/2.1.4

For interfaces with interface connection or circuit connections, running serialize() on the object fails, most likely due to some issue to gather certain attributes for the object:

>>> nb.dcim.interfaces.get(2).interface_connection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oysteigy/pynetbox/lib/python2.7/site-packages/pynetbox/lib/response.py", line 83, in __repr__
    return str(self)
  File "/home/oysteigy/pynetbox/lib/python2.7/site-packages/pynetbox/lib/response.py", line 80, in __str__
    return self.name or ''
  File "/home/oysteigy/pynetbox/lib/python2.7/site-packages/pynetbox/lib/response.py", line 66, in __getattr__
    raise AttributeError('object has no attribute "{}"'.format(k))
AttributeError: object has no attribute "name"

Looks ok in the database(?)

netbox=# select * from dcim_interfaceconnection where interface_a_id = 2 OR interface_b_id = 2;
 id | connection_status | interface_a_id | interface_b_id
----+-------------------+----------------+----------------
  1 | t                 |              2 |              1

Same error for serialize()

>>> nb.dcim.interfaces.get(2).serialize()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oysteigy/pynetbox/lib/python2.7/site-packages/pynetbox/lib/response.py", line 175, in serialize
    current_val = current_val.value
  File "/home/oysteigy/pynetbox/lib/python2.7/site-packages/pynetbox/lib/response.py", line 66, in __getattr__
    raise AttributeError('object has no attribute "{}"'.format(k))
AttributeError: object has no attribute "value"

Looks like this only occurs for interfaces with "circuit_termination" or "interface_connection" set. 

>>> nb.dcim.interfaces.get(4).serialize()
{u'lag': None, u'mgmt_only': True, u'name': u'Vlan1337', u'mac_address': None, u'enabled': True, u'circuit_termination': None, u'mtu': None, u'interface_connection': None, u'form_factor': 0, u'device': 3, u'is_connected': False, u'id': 4, u'description': u''}

**Comment by oysteingy** [comment]
Tried to debug this, 

$ cat nb.py
import pynetbox
nb = pynetbox.api('http://127.0.0.1:8080',token='67be12a6a37ce15d55ed2942173ee6747870eeaf')
nb.dcim.interfaces.get(2).serialize()

imported pdb and set breakpoint in __getattr__ in response.py

$ python  nb.py
> /home/oysteigy/pynetbox/lib/python2.7/site-packages/pynetbox/lib/response.py(62)__getattr__()
-> if self.has_details is False and k != 'keys':
(Pdb) k
'keys'
(Pdb) self.has_details
False

(Pdb) self._meta
[(u'url', u'http://metanol/api/dcim/devices/2/'), (u'display_name', u'router2'), (u'id', 2), (u'name', u'router2')]
(Pdb) self.api_kwargs
{'token': '67be12a6a37ce15d55ed2942173ee6747870eeaf', 'version': '2.1', 'private_key': None, 'private_key_file': None, 'base_url': 'http://127.0.0.1:8080/api'}
(Pdb) self.endpoint_meta
{}
(Pdb) self.default_ret
<class 'pynetbox.lib.response.Record'>
(Pdb) self.url
u'http://metanol/api/dcim/devices/2/'
(Pdb) self._meta
[(u'url', u'http://metanol/api/dcim/devices/2/'), (u'display_name', u'router2'), (u'id', 2), (u'name', u'router2')]

The URL here raised my eyebrows as it's different from base_url. 

(Pdb) self.values
*** ConnectionError: HTTPConnectionPool(host='metanol', port=80): Max retries exceeded with url: /api/dcim/devices/2/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6bb86de890>: Failed to establish a new connection: [Errno 111] Connection refused',))


I changed the nginx config so the API would be accessible via http://metanol, and tried again:

> /home/oysteigy/pynetbox/lib/python2.7/site-packages/pynetbox/lib/response.py(62)__getattr__()
-> if self.has_details is False and k != 'keys':
(Pdb) self.has_details
False
(Pdb) k
'keys'


(Pdb) self.values
*** AttributeError: object has no attribute "values"

**ding ding ding**

(Pdb) self.has_details
True
(Pdb) self._meta
[(u'url', u'http://metanol/api/dcim/devices/2/'), (u'display_name', u'router2'), (u'id', 2), (u'name', u'router2'), (u'status', {u'value': 1, u'label': u'Active'}), (u'primary_ip', {u'url': u'http://metanol/api/ipam/ip-addresses/23/', u'id': 23, u'family': 4, u'address': u'1.0.0.244/24'}), (u'device_role', {u'url': u'http://metanol/api/dcim/device-roles/7/', u'slug': u'router', u'id': 7, u'name': u'Router'}), (u'display_name', u'router2'), (u'name', u'router2'), (u'site', {u'url': u'http://metanol/api/dcim/sites/1/', u'slug': u'dc-oslo', u'id': 1, u'name': u'dc-oslo'}), (u'comments', u''), (u'rack', None), (u'asset_tag', None), (u'platform', None), (u'parent_device', None), (u'primary_ip4', {u'url': u'http://metanol/api/ipam/ip-addresses/23/', u'id': 23, u'family': 4, u'address': u'1.0.0.244/24'}), (u'device_type', {u'url': u'http://metanol/api/dcim/device-types/1/', u'model': u'ASR1000', u'id': 1, u'slug': u'asr1000', u'manufacturer': {u'url': u'http://metanol/api/dcim/manufacturers/2/', u'slug': u'cisco', u'id': 2, u'name': u'Cisco'}}), (u'primary_ip6', None), (u'position', None), (u'serial', u''), (u'face', None), (u'custom_fields', {u'TF_AS': None}), (u'id', 2), (u'tenant', None)]

**Comment by oysteingy** [comment]
Looks like this is related to nested hierarchies:

>>> nb.dcim.interfaces.get(2).form_factor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oysteigy/pynetbox/lib/python2.7/site-packages/pynetbox/lib/response.py", line 83, in __repr__
    return str(self)
  File "/home/oysteigy/pynetbox/lib/python2.7/site-packages/pynetbox/lib/response.py", line 80, in __str__
    return self.name or ''
  File "/home/oysteigy/pynetbox/lib/python2.7/site-packages/pynetbox/lib/response.py", line 66, in __getattr__
    raise AttributeError('object has no attribute "{}"'.format(k))
AttributeError: object has no attribute "name"

form_factor is a dict-in-dict, but it does not contain any key called name.

 "id": 2,
  "device": {
    "id": 2,
    "url": "http://metanol/api/dcim/devices/2/",
    "name": "router2",
    "display_name": "router2"
  },
  "name": "gi2/2/2",
  "form_factor": {
    "value": 1000,
    "label": "1000BASE-T (1GE)"
  },

**Comment by zachmoody** [comment]
Hey @oysteingy thanks for the report and debugging this. The NetBox interfaces endpoint changed recently and pynetbox hasn't accounted for it. Will work on getting it updated soon.
