### ISSUE TITLE
SERVER ERROR when creating device BUT updates SUCCESSFULLY on Netbox

### ISSUE THREAD

**Issue by etiensilvio205** [digitalocean/pynetbox#93]
Hello,

I'm actually developing an app which works with Netbox. The app makes use of the Pynetbox client API to add/update/delete devices to Netbox. Due to an issue, i updated my Netbox local version to V2.4.4 and i'm using Pynetbox 3.4.6. When i create a device via the API the device is SUCCESSFULLY created on Netbox but returns an error on the command line (I'm using the command to test the API). Can you please help me with that?
P.S I didn't have this issue when using version 2.3.3 of Netbox.

Code for create: 

**nb.dcim.devices.create([
			{
			"name": "device name",
			"device_role": "device role",
			"site": "role",
			"device_type": "device type",
			"serial": "serial number",
			"status": "status",
			"rack":  "rack",
			"face": "face"
			}
			])**

Error:

**<!DOCTYPE html>
<html lang="en">

<head>
    <title>Server Error</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.
css">
    <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.min
.css">
    <meta charset="UTF-8">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-danger" style="margin-top: 200px">
                    <div class="panel-heading">
                        <strong>
                            <i class="fa fa-warning"></i>
                            Server Error
                        </strong>
                    </div>
                    <div class="panel-body">

                            <p>
                                There was a problem with your request. Please contact an administrator.
                            </p>

                        <hr />
                        <p>
                            The complete exception is provided below:
                        </p>
<pre><strong>&lt;type &#39;exceptions.KeyError&#39;&gt;</strong><br />u&#39;1&#39;</pre>
                        <p>
                            If further assistance is required, please post to the <ahref="https://groups.google.com/forum/#!forum/netbox-discuss">NetBox mailing list</a>.
                        </p>
                        <div class="text-right">
                            <a href="/" class="btn btn-primary">Home Page</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>**

**Comment by zachmoody** [comment]
Can you share exactly what the list you're passing to create looks like. I'm not able to recreate on v2.4.4 - Might also want to try updating NetBox if it's still a problem.
